### ISSUE TITLE
Nvim-tree opens on half of the screen when file is opened

### ISSUE THREAD

**Issue by adamwojt** [NvChad/NvChad#606] opened 2021-11-21 00:40 UTC
**Describe the bug**

**To Reproduce**
1. Open with `nvim`
2. Ctrl + n -> size is correct, around 20% of screen
3. Choose file and open it
4. See bug

**Expected behavior**
Nvim-tree should keep it's original size

**Screenshots**
![image](https://user-images.githubusercontent.com/45100954/142744977-0a79f5a1-c779-4610-9f40-86f556d1ecb8.png)

![image](https://user-images.githubusercontent.com/45100954/142744971-45963d69-4fdf-40a9-bb07-b918f7519a4d.png)

**Desktop (please complete the following information):**
 - Arch
 - Kitty
 - NVIM v0.5.1

**Additional context**
Also when opening with `nvim .` I don't get auto open even when option is enabled.

**Comment by siduck** [comment] 2021-11-21 01:14
this looks like an upstream issue!

**Comment by siduck** [comment] 2021-11-21 02:02
minimal config : 
https://user-images.githubusercontent.com/59060246/142746442-e1e082c7-d857-4f0f-9960-f1ba39a832cb.mp4

I cant reproduce the issue you have tho
https://user-images.githubusercontent.com/59060246/142746493-1d7e32a4-baab-4f9e-9063-0f74323e83a4.mp4

**Comment by adamwojt** [comment] 2021-11-21 02:24
Thanks! Even after syncing ? Maybe some updates were made to plugins ?

**Comment by peppapig450** [comment] 2021-11-28 20:16
What terminal is that? it could be a padding issue maybe

**Comment by peppapig450** [comment] 2021-11-29 19:04
this happened to me yesterday too on tty and sshed into a vm with windows terminal

**Comment by chovanecadam** [comment] 2021-12-17 16:29
I have a similar issue. After closing a buffer, the Tree sometimes takes the entire width of the window. Selecting another buffer doesn't help, it is still very large. I have to close and open the tree again. There's a video. Aside from a different theme I haven't edited the NvChad configuration.

https://user-images.githubusercontent.com/23148601/146576549-d3fa502c-0a30-4f49-bb70-aba3958e57e4.mp4

**Comment by siduck** [comment] 2021-12-17 17:22
@chovanecadam does this happen when you close the buffer with :bd?

**Comment by adamwojt** [comment] 2021-12-21 12:19
> What terminal is that? it could be a padding issue maybe

It's Kitty.

**Comment by namnh2204** [comment] 2022-01-02 15:00
I am facing the same issue too.

**Comment by siduck** [comment] 2022-01-06 15:35
do you guys face this issue when doing :bd instead of leader x?

**Comment by nank1ro** [comment] 2022-01-07 14:05
> do you guys face this issue when doing :bd instead of leader x?

Facing the same issue, and yes seems like this happens only when using `:bd`, while with `<leader>x` seems working fine

**Comment by adamwojt** [comment] 2022-02-07 08:39
Just before this is closed, can everyone who faced same issue give their terminal name and version. Maybe it is upstream. @namnh2204 @namnh2204

**Comment by nank1ro** [comment] 2022-02-07 09:56
> Just before this is closed, can everyone who faced same issue give their terminal name and version. Maybe it is upstream. @namnh2204 @namnh2204

OS: MacOS Monterey 12.1
Terminal: iTerm2 3.4.12
Neovim version: v0.6.1

**Comment by siduck** [comment] 2022-02-07 13:37
> Just before this is closed, can everyone who faced same issue give their terminal name and version. Maybe it is upstream. @namnh2204 @namnh2204
> 
> EDIT, mine is:
> 
> ```
> OS: &7 x86_64 Arch Linux
> Kernel: 5.15.13
> Shell: zsh
> Terminal: kitty 0.24.1
> ```

does this issue persist with a minimal config?

**Comment by DucMinhCao** [comment] 2022-03-10 13:32
I'm facing the same issue with nvim-tree, when i open a file, nvim tree opens on half of the screen
```
OS: KDE Manjaro 21.2.4 Qonos
Kernel: 55.13.19-2-MANJARO
Shell: zsh
Terminal: alacritty
```
![image](https://user-images.githubusercontent.com/34432166/157672103-36f823f4-3f89-4d23-86d6-e44fcc2d64eb.png)

**Comment by martispyc** [comment] 2022-03-10 18:57
Facing the same issue
```
Using WSL Ubuntu 20.04
Shell: zsh
Termianl: Windows Terminal
```

**Comment by siduck** [comment] 2022-03-11 00:41
https://user-images.githubusercontent.com/59060246/157779500-74cbdf27-8794-49f3-9140-4bbfaf9bc55f.mp4

i dont face this issue,when was the last time u updated nvchad and did packersync?

**Comment by DucMinhCao** [comment] 2022-03-11 01:11
@siduck just updated it yesterday. Btw i dont think this is nvchad's bug, i'll get help from nvim-tree

**Comment by siduck** [comment] 2022-03-11 02:43
> @siduck just updated it yesterday. Btw i dont think this is nvchad's bug, i'll get help from nvim-tree

Maybe, but first test it with a minimal config or tell me the steps to produce this bug. I'm unable to reproduce this bug

**Comment by martispyc** [comment] 2022-03-11 07:28
For me, I really liked the NvChad way of doing things so I just took their config and modified it a bit. Everything worked fine until I removed the colors folder and added nvim-notify. I tried to remove packer and cloned a fresh NvChad but the problem still occurred.

**Comment by siduck** [comment] 2022-03-11 08:55
the nvimtree problem?

**Comment by martispyc** [comment] 2022-03-11 09:22
yes

**Comment by TikiCat7** [comment] 2022-03-11 11:49
having the same issue from today after packer sync

**Comment by comchieu3mon** [comment] 2022-03-12 02:10
You all can go to https://github.com/kyazdani42/nvim-tree.lua/issues/1071 to see the fix. It works for me :smile:

**Closed** 2022-03-12 03:12 UTC
