### ISSUE TITLE
Shift+K doesn't work

### ISSUE THREAD

**Issue by uyha** [NvChad/NvChad#1124] opened 2022-05-24 13:29 UTC
**Describe the bug**
`Shift-K` in man or help page doesn't bring up the target page

**To Reproduce**
1. Run `nvim +help man`
2. Search for `credits`
3. `Shift+K`

**Expected behavior**
After pressing `Shift+K` on some keyword, the reference page for the keyword should be brought up.

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 20.04
 - Terminal: Alacritty
 - Version of Neovim: NVIM v0.7.0

**Additional context**
This happens with the bare config from NvChad, no custom configs are loaded

**Comment by siduck** [comment] 2022-05-24 13:38
K is used here
![image](https://user-images.githubusercontent.com/59060246/170048592-1c916eae-9640-46a0-91b7-799e40716e49.png)

**Comment by siduck** [comment] 2022-05-24 13:39
![image](https://user-images.githubusercontent.com/59060246/170049091-f620953e-b1b4-4ea8-beef-bbf27b02721c.png)


one of the default lsp mappings

**Comment by uyha** [comment] 2022-05-24 13:42
but it shouldn't affect `man` or `help`, right? or will it bind regardless there is an language server attached or not?

**Comment by siduck** [comment] 2022-05-24 13:44
a sec!

**Comment by nullchilly** [comment] 2022-05-24 14:08
afaik you also can't set custom filetype in whichkey without "hacking" autocmds.

**Comment by LeonHeidelbach** [comment] 2022-05-24 14:11
@siduck we could just register the lsp mappings in the lspconfig setup and remove them from the list of default mappings.

**Comment by siduck** [comment] 2022-05-24 14:11
oh no :c !! Will wait for @LeonHeidelbach 's input, if its not possible then lets nuke whichkey from nvchad :bomb:

**Comment by siduck** [comment] 2022-05-24 14:12
> @siduck we could just register the lsp mappings in the lspconfig setup and remove them from the list of default mappings.

ah but i'd want all of the mappings to be in the same file

**Comment by LeonHeidelbach** [comment] 2022-05-24 14:18
> maybe while registering all mappings, we could make a check to skip lsp mappings :thinking:  and register them in the lspconfig

@siduck yes, we could create an exclusion list that will skip specified mappings and add them to a setup function of a specific plugin. I'll think about a clever solution for that later. But nuking which-key is not a good idea, I really like the current setup. If people don't want to use it they don't have to.

**Comment by LeonHeidelbach** [comment] 2022-05-26 17:08
> @LeonHeidelbach any way to exclude lspconfig mappings? like map them only when lsp server is attached to buffer , we had this before https://github.com/NvChad/NvChad/pull/992/files . But we dont use the old mapping function now right D:

@uyha Implemented the above in here https://github.com/NvChad/NvChad/pull/1130. After @siduck confirmed that everything's also working on his end, we'll merge. You could in the meantime check the `dev` branch out yourself and see if it works for you.

**Comment by LeonHeidelbach** [comment] 2022-05-26 17:13
@uyha nice, so as soon as @siduck wakes up in the morning (his time) he'll have a look at it and merge into main.

**Comment by AlessandroZanatta** [comment] 2022-05-26 18:21
> so if u want to use K then disable it and re-map it


Sorry to barge in like this, but I didn't feel a new issue was needed (as this is somewhat related).
How can I add a custom mapping, like, in general? 

I've disabled LSP and I've tried to add `vim.cmd "map K :Man<CR>" ` to my `custom/init.lua`, but that doesn't work at all.
Mapping it while in nvim (i.e. `:map K :Man<CR>`) works as expected.
I also wanted to add a mapping to close stuff faster (i.e. `map <leader>q :q<CR>`), but this doesn't work either.

Sorry if this is out of scope or a noob question, I am not yet quite accustomed to nvim or lua. After some hours, I really cannot wrap my head around this.

**Comment by LeonHeidelbach** [comment] 2022-05-26 18:27
@AlessandroZanatta please read the documentation https://nvchad.github.io/config/Mappings.

**Comment by AlessandroZanatta** [comment] 2022-05-26 18:30
> @AlessandroZanatta please read the documentation https://nvchad.github.io/config/Mappings.

Looks like I'm blind then, I'm very sorry about that.

**Comment by siduck** [comment] 2022-05-27 00:37
should be fix\ed now, update nvchad

**Closed** 2022-05-27 00:37 UTC
