### ISSUE TITLE
Telescope breaks when adding plugins

### ISSUE THREAD

**Issue by nift4** [NvChad/NvChad#230] opened 2021-08-11 08:24 UTC
**Describe the bug**
When I add tmux or zshcomp (one is enough) plugins as described in Chad User Configs wiki, Telescope breaks. It says No such editor command.

**To Reproduce**
1. Add tmux plugin as described on wiki
2. :PackerSync and :PackerCompile
3. Restart nvim
4. Try to use telescope
5. See error

**Expected behavior**
It is supposed to work.

**Screenshots**
![Bildschirmfoto von 2021-08-11 10-21-38](https://user-images.githubusercontent.com/36458596/128995431-74f8b28c-4b70-49ee-bdb6-fb55a98f2e49.png)

**Desktop (please complete the following information):**
 - Operating System: Debian testing
 - Terminal: GNOME terminal
 - Version of Neovim
```NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-5xboCk/neovim-0.5.0+ubuntu2+git202108101753-c5baba065-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-5xboCk/neovim-0.5.0+ubuntu2+git202108101753-c5baba065-d569569c9/build/config -I/build/neovim-5xboCk/neovim-0.5.0+ubuntu2+git202108101753-c5baba065-d569569c9/src -I/build/neovim-5xboCk/neovim-0.5.0+ubuntu2+git202108101753-c5baba065-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-5xboCk/neovim-0.5.0+ubuntu2+git202108101753-c5baba065-d569569c9/build/src/nvim/auto -I/build/neovim-5xboCk/neovim-0.5.0+ubuntu2+git202108101753-c5baba065-d569569c9/build/include
Übersetzt von buildd@lgw01-amd64-030

Features: +acl +iconv +tui
See ":help feature-compile"

          System-vimrc-File: "$VIM/sysinit.vim"
    Preset for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Additional context**
https://github.com/nift4/NvChad/blob/3768be69529b99fcaa65f5b746439b578000eb70/lua/pluginList.lua#L262-L267
This is how I added the tmux plugin

**Comment by Vanderscycle** [comment] 2021-08-11 17:38
I am having this issue as well but its on recent/new install as I have the same setup at home where telescope works but doesn't work on my work computer which is a fresh install

**Comment by dmatos2012** [comment] 2021-08-12 07:42
Yeah, same here. Every time I add a new package in `pluginList.lua` and do any `:PackerSync` or `:PackerCompile` get the telescope error. If remove the plugin, everything gets "fixed" again. 

Anyone has discovered why yet?:)

**Comment by nift4** [comment] 2021-08-12 10:16
when I just enter :Telescope, it says no such editor command, packer tries to update it and says I have to restart nvim, when I try again it repeats.

**Comment by siduck76** [comment] 2021-08-12 10:23
> That is because telescope will only be loaded when typed `Telescope` instead of `Telescope find_files`
> 
> It is lazyloaded in such a way.

No

**Comment by ashincoder** [comment] 2021-08-12 11:53
@siduck76  Instead of replying to me u should try it. Open neovim and type this at first `:Telescope find_files`. Then tell me what happens.

**Comment by ashincoder** [comment] 2021-08-12 11:55
https://github.com/siduck76/NvChad/blob/main/lua/pluginList.lua in line 155 Telescope is loaded on on cmd Telescope

**Comment by siduck76** [comment] 2021-08-12 11:58
> @siduck76 Instead of replying to me u should try it. Open neovim and type this at first `:Telescope find_files`. Then tell me what happens.



> @siduck76 Instead of replying to me u should try it. Open neovim and type this at first `:Telescope find_files`. Then tell me what happens.

![image](https://user-images.githubusercontent.com/59060246/129192892-e3f5cc7a-f38f-40ae-8402-4879c235501a.png)

**Comment by ashincoder** [comment] 2021-08-12 11:59
I don't know if ur doing what I'm saying but I get some errors.

**Comment by siduck76** [comment] 2021-08-12 12:00
> https://github.com/siduck76/NvChad/blob/main/lua/pluginList.lua in line 155 Telescope is loaded on on cmd Telescope

This issue is very random , NvChad has been lazy loading telescope since month.

**Comment by ashincoder** [comment] 2021-08-12 12:00
But first try to solve the problem #230 instead of coming to hunt me.

**Comment by siduck76** [comment] 2021-08-12 12:00
> I don't know if ur doing what I'm saying but I get some errors.

yes i got those before too , delete .config/nvim/plugin folder and packersync

**Comment by siduck76** [comment] 2021-08-12 12:01
> But first try to solve the problem #230 instead of coming to hunt me.

wym trying to hunt you? I just meant the issue isnt cuz of cmd "Telescope"

**Comment by siduck76** [comment] 2021-08-12 12:02
https://github.com/siduck76/NvChad/issues/217

**Comment by siduck76** [comment] 2021-08-12 12:02
https://github.com/siduck76/NvChad/issues/198

**Comment by siduck76** [comment] 2021-08-12 12:19
@dmatos2012 can you delete ~/.local/share/nvim and re-install nvchad?

**Comment by dmatos2012** [comment] 2021-08-12 12:30
@siduck76 hi siduck thans for the quick response, but I have a slightly modified version, so even if it solves it for me, might not for the others. but what is the intent? so perhaps I can try to pinpoint what it is and tell here if I find the error

**Comment by siduck76** [comment] 2021-08-12 12:36
> @siduck76 hi siduck thans for the quick response, but I have a slightly modified version, so even if it solves it for me, might not for the others. but what is the intent? so perhaps I can try to pinpoint what it is and tell here if I find the error

there was a previous issue where the user ran packercompile before packersync which was causing the same issue as this. Now packer will automatically compile after packersync . test latest nvchad locally and let me know if you still have the error.

**Comment by G-Rowell** [comment] 2021-08-12 13:06
Hmmmm, 

I'm hoping to look into this in the next few weeks, as I've been getting this issue a fair amount too.

[I think it's to do with this section](https://github.com/siduck76/NvChad/blob/main/lua/plugins/telescope.lua#L73-L88), as I haven't seen this in any other config repo (be it a large sibling to NvChad, or the personal config of Packer's author etc...)

It's weird for sure :face_with_head_bandage:

**Comment by JustSage** [comment] 2021-08-12 13:44
> Hmmmm,
> 
> I'm hoping to look into this in the next few weeks, as I've been getting this issue a fair amount too.
> 
> [I think it's to do with this section](https://github.com/siduck76/NvChad/blob/main/lua/plugins/telescope.lua#L73-L88), as I haven't seen this in any other config repo (be it a large sibling to NvChad, or the personal config of Packer's author etc...)
> 
> It's weird for sure 🤕

Personally I don't have this in my config and it all works fine. This is a fail-safe code block for telescope extensions.
Should note if you don't have [ueberzug](https://github.com/seebye/ueberzug) installed (which is only available for Linux),  [telescope-media-files](https://github.com/nvim-telescope/telescope-media-files.nvim) is not going to work or may cause issues with telescope.

**Comment by Akianonymus** [comment] 2021-08-12 13:56
as @JustSage said, it's just a fail safe code

means it will trigger after failing, not before, so i don't see how that causes any issue.

But one could remove and see if the issue goes away, if it does, let's just remove the code.

**Comment by dmatos2012** [comment] 2021-08-12 14:03
@siduck76  I removed `/.local/share/nvim and reinstalled and didnt help`. Also, I removed the telescope section mentioned and that also didnt work. :( . This is very strange

**Comment by siduck76** [comment] 2021-08-12 14:09
@dmatos2012  

https://user-images.githubusercontent.com/59060246/129211674-24f80385-d2d6-4b35-a8a1-abbd6586ee6d.mp4

works for me even after a fresh install , very weird :c

**Comment by dmatos2012** [comment] 2021-08-12 14:20
Yeah, lets wait for others to see what they report, because at least for me not. But as soon as I remove the "extra" package, it works again. Maybe its time to hijack tjs stream and ask him why this happens :P.

**Comment by siduck76** [comment] 2021-08-12 14:21
> Yeah, lets wait for others to see what they report, because at least for me not. But as soon as I remove the "extra" package, it works again. Maybe its time to hijack tjs stream and ask him why this happens :P.

I hope this isnt a nvchad issue xD

**Comment by nift4** [comment] 2021-08-12 14:44
> @dmatos2012
> 
>  simplescreenrecorder-2021-08-12_19.16.59.mp4 
> works for me even after a fresh install , very weird :c

Telescope works here, too. Just when I add a extra plugin it breaks.

**Comment by dmatos2012** [comment] 2021-08-12 14:46
@siduck76  so its definitely related to `:PackerSync`. I add the plugin again, and just do `:PackerInstall` and then its ok, but when I do `Sync` it brings the error. Also, would it make sense to build nvim from source? Im using `NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3.
`

So not from ubuntu ppas but from source or the stable 0.5? Just to see if could be also related to that. 

nb: Not same issue, but similar.[lunarvim]( https://github.com/LunarVim/LunarVim/issues/268)

**Comment by dmatos2012** [comment] 2021-08-12 14:48
Yes, because `Turning it on and off didnt work :(`

**Comment by siduck76** [comment] 2021-08-12 14:59
> Yes, because `Turning it on and off didnt work :(`

Could you try this  https://github.com/siduck76/NvChad/issues/230#issuecomment-897660962

**Comment by JustSage** [comment] 2021-08-12 15:03
> @siduck76 so its definitely related to `:PackerSync`. I add the plugin again, and just do `:PackerInstall` and then its ok, but when I do `Sync` it brings the error. Also, would it make sense to build nvim from source? Im using `NVIM v0.6.0-dev Build type: RelWithDebInfo LuaJIT 2.1.0-beta3. `
> 
> So not from ubuntu ppas but from source or the stable 0.5? Just to see if could be also related to that.
> 
> nb: Not same issue, but similar.[lunarvim](https://github.com/LunarVim/LunarVim/issues/268)

Usually fixing the telescope issue involves:
`rm -r -f <path-to-nvim/plugin>` -> `PackerSync` -> `PackerCompile` (**not** `PackerInstall`) -> refresh buffer.
If this does not help it means you could have either a typo within pluginList or within a configuration file.

**Comment by dmatos2012** [comment] 2021-08-12 16:11
@JustSage  that doesnt work. And I am 100% sure I dont have a typo. 

@siduck76 ON the other hand, if I load telescope , like in their readme 
```
use {
  'nvim-telescope/telescope.nvim',
  requires = { {'nvim-lua/plenary.nvim'} }
}
```
it works perfectly, and I can add as many plugins as I want.

but in that way, I am not sure how to add our own `require (plugins.telescope)` lua file. So at least with default configuration, it works

**Comment by siduck76** [comment] 2021-08-12 16:14
> @JustSage  that doesnt work. And I am 100% sure I dont have a typo. 
> 
> @siduck76 ON the other hand, if I load telescope , like in their readme 
> ```
> use {
>   'nvim-telescope/telescope.nvim',
>   requires = { {'nvim-lua/plenary.nvim'} }
> }
> ```
> it works perfectly, and I can add as many plugins as I want.
> 
> but in that way, I am not sure how to add our own `require (plugins.telescope)` lua file. So at least with default configuration, it works

Oki I'll make some changes

**Comment by Vanderscycle** [comment] 2021-08-12 16:17
@siduck76 I know we want everything lazy loaded but telescope is a cornerstone to neovim and loading by default isn't a bad thing.

**Comment by siduck76** [comment] 2021-08-12 17:14
It fixes the issue for me : 
https://user-images.githubusercontent.com/59060246/129239691-a5cd57f0-b072-4210-a2ec-62278d7c2aa1.mp4

**Comment by dmatos2012** [comment] 2021-08-12 18:41
> It fixes the issue for me :
> https://user-images.githubusercontent.com/59060246/129239691-a5cd57f0-b072-4210-a2ec-62278d7c2aa1.mp4

awesome! my config is slightly different now, but this fixed it for sure. You are awesome, thank you :)  :rocket:

**Comment by siduck76** [comment] 2021-08-13 07:21
> > It fixes the issue for me :
> > https://user-images.githubusercontent.com/59060246/129239691-a5cd57f0-b072-4210-a2ec-62278d7c2aa1.mp4
> 
> awesome! my config is slightly different now, but this fixed it for sure. You are awesome, thank you :)  . Could you shed light on what was the problem? @siduck76

Idk much but 3 plugins (telescope , telescope fzf native and telescope-media ) were triggering on the same cmd ( "Telescope "). So maybe packer gets messed up deciding which one to load first! since they all load at the same cmd , so I removed the cmd condtion for fzf native and telescope media so they will be loaded before telescope rather than along with telescope . Since telescope loads on "cmd Telescope" so whenever telecope loads , it will load the telescope config ( lua/plugins/telescope.lua) and that telescope config has those 2 plugins ( telescope fzf native and media one , these arent even loaded yet since they load at cmd telescope by default) . so these plugins are loaded after telescope BUT TELESCOPE CONFIG INVOKES THOSE 2 PLUGINS BEFORE THEY EVEN LOAD. So using cmd telecsope condition for telescope plugin only fixed the issue.

**Comment by siduck76** [comment] 2021-08-16 17:34
@dmatos2012 @nift4 I assume this issue is fixed . I'll close this , feel free to open it if the issue still persists.

**Closed by siduck76** 2021-08-16 17:34 UTC
Labels: bug
