### ISSUE TITLE
nvchad installer is totally broken

### ISSUE THREAD

**Issue by IDBEHOLDS** [NvChad/NvChad#1019] opened 2022-05-04 08:50 UTC
```
os: archlinux
```
```
 nvim -v      
NVIM v0.7.0-dev+1290-ge7391191e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

```
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim
rm -rf ~/.cache/nvim
```
```
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
nvim +'hi NormalFloat guibg=#1e222a' +PackerSync
```
```
Error detected while processing /home/user/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/user/.config/nvim/init.lua:16: Error
loading core.mappings

/home/user/.config/nvim/lua/core/mappings.lua:67: attempt to call local 'user_cmd
' (a nil value)
stack traceback:
        [C]: in function 'error'
        /home/user/.config/nvim/init.lua:16: in main chunk
Error detected while processing command line:
E492: Not an editor command: PackerSync
Press ENTER or type command to continue
```

**Comment by siduck** [comment] 2022-05-04 09:55
https://user-images.githubusercontent.com/59060246/166660408-c8556555-8e3d-4d5b-9ced-964b3f3b2a99.mp4

Unable to reproduce the issue, use release version of nvim 0.7

**Comment by GreatestOfAllTimee** [comment] 2022-05-04 12:25
> ```
> nvim -v      
> NVIM v0.7.0-dev+1290-ge7391191e
> Build type: RelWithDebInfo
> LuaJIT 2.1.0-beta3
> ```

If this issue is regarding to Nvchad and he install Neovim with [latest v0.7+ (manual build)](https://github.com/neovim/neovim/commits/release-0.7)  than Nvchad should follow up. I believe they (neovim) fix major bugs from previous released.

**Comment by GreatestOfAllTimee** [comment] 2022-05-04 12:28
Can you share your custom config?

**Comment by peppapig450** [comment] 2022-05-05 01:10
The lua api is different in nightly so things break is what I am assuming

**Comment by siduck** [comment] 2022-05-05 01:36
> Can you share your custom config?

@IDBEHOLDS doesnt has any ig

**Comment by peppapig450** [comment] 2022-05-05 01:37
user_cmd is an nvim api related thing which is why it fails on the nightly. Switch to the stable version and it will work.

**Comment by GreatestOfAllTimee** [comment] 2022-05-05 01:39
> The lua api is different in nightly so things break is what I am assuming

Nightly v0.8?

**Comment by peppapig450** [comment] 2022-05-05 01:39
`NVIM v0.7.0-dev+1290-ge7391191e`

**Comment by GreatestOfAllTimee** [comment] 2022-05-05 01:53
I can confirm that, I am running `NVIM v0.7.1-dev` from the https://github.com/neovim/neovim/tree/release-0.7 branch and it works fine.

**Comment by peppapig450** [comment] 2022-05-05 02:33
idk then i just tried on nightly too and it works

**Comment by siduck** [comment] 2022-05-05 02:50
Its better to use https://github.com/neovim/neovim/releases/tag/v0.7.0

**Comment by GreatestOfAllTimee** [comment] 2022-05-05 03:42
> Its better to use https://github.com/neovim/neovim/releases/tag/v0.7.0

If you see the current issue of Neovim there are several bugs from `v0.6+` should be fixed in `v0.7.0` released but unfortunately not. 

- **Open since 6 Apr 2021 (closed on 25 Apr 2022)** https://github.com/neovim/neovim/issues/14304

- **Open since 4 Sep 2021** https://github.com/nvim-treesitter/nvim-treesitter/issues/1788 (https://github.com/neovim/neovim/pull/18400)

- https://github.com/neovim/neovim/issues/18236 (**releated issue from Nvchad** https://github.com/NvChad/NvChad/issues/1001)

- https://github.com/neovim/neovim/issues/18148

> idk then i just tried on nightly too and it works

that what I thought, maybe this issue has nothing to do with the Neovim version or maybe he using old nightly build from v0.7.0

**Comment by peppapig450** [comment] 2022-05-05 03:43
i think its an old nightly build

**Comment by IDBEHOLDS** [comment] 2022-05-05 10:58
Thank you guys, yeah i use neovim git from yay repo with default lspconfig.lua. 
So every time i have troubles with NVupdate or PackerSync.

**Closed** 2022-05-05 10:58 UTC

**Comment by siduck** [comment] 2022-05-05 11:01
@IDBEHOLDS use neovim package from official arch repo :)

**Comment by xingheng** [comment] 2022-05-09 02:50
Same here, the latest version in homebrew is still 0.5. Downloading the [0.7](https://github.com/neovim/neovim/releases/tag/v0.7.0) resolved it, but here is a new issue:
```
E484: Can't open file /share/nvim/syntax/syntax.vim
```

**Comment by siduck** [comment] 2022-05-09 03:14
Im unable to reproduce the issue as I dont use macos!

**Comment by MaikolSoro** [comment] 2022-09-25 02:37
I have the same problem with Nvcad in parrot?

**Comment by siduck** [comment] 2022-09-25 03:03
> I have the same problem with Nvcad in parrot?

make sure you use latest stable release of neovim which is 0.7.2 . 

parrot is based on debian so it has an older version of nvim, try https://github.com/MordechaiHadad/bob
