### ISSUE TITLE
code Display error 

### ISSUE THREAD

**Issue by MaxJohnXiang** [NvChad/NvChad#405] opened 2021-08-30 03:39 UTC
![image](https://user-images.githubusercontent.com/24894004/131281703-2dbcefd9-ef2f-4031-a677-be3b06ddcda5.png)

When i move the cursor , the code display correct. 

![image](https://user-images.githubusercontent.com/24894004/131281754-4c6f6e17-db1d-487c-8725-67d13e8f5430.png)

**Comment by MaxJohnXiang** [comment] 2021-08-30 03:58
![image](https://user-images.githubusercontent.com/24894004/131283352-ef715fbb-09c6-4472-9770-cf64833ae50d.png)

**Comment by MaxJohnXiang** [comment] 2021-08-30 08:30
![image](https://user-images.githubusercontent.com/24894004/131310307-9489080d-a537-4259-839b-cd41b82b0ca9.png)

**Comment by Daniel-Boll** [comment] 2021-09-05 18:17
It's also happening with me.

![image](https://user-images.githubusercontent.com/43689101/132137213-3a2e6b4b-23c7-4dd4-9a69-1929ec163c07.png)

I started typing and the buffer didn't refresh or something like that, I have to move to another line in order to it display correctly.

![image](https://user-images.githubusercontent.com/43689101/132137231-130fcaca-3d7c-4344-bc05-5c5f4ce616d7.png)

And also a `K` equivalent but automatically and don't close on ESC is being super annoying

![image](https://user-images.githubusercontent.com/43689101/132137119-bd5ab61e-3761-4cfc-9d87-ee402702905e.png)

It started when I happen to have my cursor over the line 23, and then when I move from there it didn't disappeared and it stays at the screen for how long it wants

**Comment by siduck76** [comment] 2021-09-06 00:10
idk about this , maybe this depends on the LSP server too . Try setting 
```
update_in_insert = false,
```

To true 

in lua/plugins/configs/lspconfig.lua

**Comment by siduck76** [comment] 2021-09-10 10:38
@Daniel-Boll @MaxJohnXiang lspdiagnostics updates in normal mode, enable the update_in_insert so it'll update in insert mode too

**Comment by Daniel-Boll** [comment] 2021-09-10 18:21
The first time it didn't worked out, I just gave up for a while, then I download Neovide and tried the config again and it worked out just as fine, but my `update_in_insert` is still set to `false` :thinking:.

**Comment by siduck76** [comment] 2021-09-11 00:39
> The first time it didn't worked out, I just gave up for a while, then I download Neovide and tried the config again and it worked out just as fine, but my `update_in_insert` is still set to `false` 🤔.

Because that option is disabled by default

**Comment by lukeberry99** [comment] 2021-09-11 19:07
I'm getting the same issue, I've only used the `tsserver` LSP for typescript, but it happens whenever I edit a line that has a LSP message on it, ![image](https://user-images.githubusercontent.com/1644147/132958749-f0f0671b-b19d-4325-99fa-0ea1548adb39.png)

Returning to normal mode fixes the line

![image](https://user-images.githubusercontent.com/1644147/132958791-90113a21-75ae-4b2c-9a2f-58d10b504d69.png)


Setting `update_in_insert` to true makes it a lot worse.

**Comment by siduck76** [comment] 2021-09-12 03:13
share me your code, I'll test it here :l

**Comment by Daniel-Boll** [comment] 2021-09-12 20:10
As I previously said I just re-installed the `(((chad)))`config and the problem was gone - after the third time. So I can't offer much help now. But I will continue investigating, as soon as I find something I'll report to this thread 🧷.

**Comment by lukeberry99** [comment] 2021-09-12 20:59
@siduck76 I'm not able to share that specific code base as it is client work, however I will whip together a small example repo and post that here.

**Comment by lukeberry99** [comment] 2021-09-12 21:39
Hi @siduck76  here is a short video demonstrating the issue as well as a link to my NvChad config. and the example repo.

You can see that when I correct the error the first key entered is not visible until I exit insert mode, it's worth noting that I have autosave enabled and that seems to trigger a redraw which may be what is fixing my issue, without autosave enabled I have to exit to normal mode, go back into insert mode and then move the cursor.

Config:
Neovim version: v0.6.0-dev+223-g384a43fe7
OS: Arch
Term: Alacritty
WM: BSPWM
NvChad Config: https://github.com/lukeberry99/NvChad
Example repe: https://github.com/lukeberry99/nvchad-example


https://user-images.githubusercontent.com/1644147/133003608-c9ee6d26-fa9c-49cf-b624-b53c9ff0b651.mp4

**Comment by siduck76** [comment] 2021-09-13 08:48
@lukeberry99 lspdiagnostics are gonna get updated in normal mode only by default , set update_in_insert to true , which will update the diagnostics in insert mode too :(

**Comment by siduck76** [comment] 2021-09-13 08:48
also why v0.6..

**Comment by lukeberry99** [comment] 2021-09-14 11:38
I've used the Nightly of nvim for a while, but the issue is apparent on v0.5 as well. Setting `update_in_insert` to true has no effect.

**Comment by dsewnr** [comment] 2021-09-16 06:00
I got the same problem.
![Screen Shot 2021-09-16 at 1 51 24 PM](https://user-images.githubusercontent.com/3303223/133557508-174ba2c4-7a0b-43ea-a428-8d6d95a9fcf0.png)

But it was solved after I tried to set the "virtual_text.spacing".

**Comment by lukeberry99** [comment] 2021-09-17 01:34
@siduck76 Here is with `update_in_insert` set to true on nvim 0.5, same OS as above but confirmed on macOS as well.

https://user-images.githubusercontent.com/1644147/133709554-ff5d8ff9-6cf3-4757-9149-4ecd65c5889a.mp4

**Comment by siduck76** [comment] 2021-09-17 01:36
looks fine , so whats the issue?

**Comment by lukeberry99** [comment] 2021-09-17 01:39
When typing the space between const and user disappears (as well as the u in user), the `c` in createUser gets repeated then is removed, this happens on every line that has an LSP message.

**Comment by siduck76** [comment] 2021-09-17 01:52
looks weird

**Comment by siduck76** [comment] 2021-09-17 01:59
https://user-images.githubusercontent.com/59060246/133711695-673af22c-3ebb-47c8-b691-69729692fda9.mp4

doesnt happen with me

**Comment by lukeberry99** [comment] 2021-09-17 02:03
Do you have `update_in_insert` set to true in that example? I'll try some other stuff and see if I can narrow down whats causing the issue.

**Comment by siduck76** [comment] 2021-09-17 02:05
> Do you have `update_in_insert` set to true in that example? I'll try some other stuff and see if I can narrow down whats causing the issue.

no

**Comment by siduck76** [comment] 2021-09-17 02:07
but I dont face the issue you're facing in update_in_insert tho

**Comment by G-Rowell** [comment] 2021-09-25 12:08
I think this is good to close maybe?

@MaxJohnXiang has not responded to this for 25+ days.

Does the root issue / bug still persist?

**Comment by Daniel-Boll** [comment] 2021-09-25 18:10
I still have somewhat of a bug only when dealing with a mongo provider file that I have

![image](https://user-images.githubusercontent.com/43689101/134781709-e3d54e2e-4321-4f7a-a6a0-8698e0a3ee44.png)

where the floating window doesn't disappear automatically I must switch buffers then it's gone. 

But the crucial display error is not bothering me no more. ¯\_(ツ)_/¯

**Comment by siduck76** [comment] 2021-09-25 18:39
> I still have somewhat of a bug only when dealing with a mongo provider file that I have
> 
> ![image](https://user-images.githubusercontent.com/43689101/134781709-e3d54e2e-4321-4f7a-a6a0-8698e0a3ee44.png)
> 
> where the floating window doesn't disappear automatically I must switch buffers then it's gone.
> 
> But the crucial display error is not bothering me no more. ¯_(ツ)_/¯

oh the floating window here is managed by lspsignature , it think this looks like an upstream issue!

**Comment by siduck76** [comment] 2021-09-26 02:01
since the code display error no longer bothers @lukeberry99 , im gonna close this!!

**Closed by siduck76** 2021-09-26 02:01 UTC
