### ISSUE TITLE
Tmux statusline color covers whole terminal

### ISSUE THREAD

**Issue by skrapi** [NvChad/NvChad#296] opened 2021-08-19 15:24 UTC
**Describe the bug**

Firstly, I really love what you are doing here, and this is a specific bug that should not be prioritized unless others experience it as well. I am not sure where to start debugging, but happy to try with some guidance.  Onto the problem:

When I ssh into a Linux machine from a MacOS machine, I enter into a tmux session and then enter neovim, the whole screen has the same color as the tmux status bar.

**To Reproduce**
1. ssh into a linux machine
2. enter tmux
3. open nvim
4. you should see a full screen of tmux statusline color

**Expected behavior**

I have shown normal behaviour in first screenshot below.

**Screenshots**

ITerm on Mac:
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/25342579/130093717-93b3d613-1b3f-4375-a318-fb9976aa150a.png">

ITerm on Mac sshed into zsh on Linux:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/25342579/130093914-c65bc130-f3a7-4c4e-8c73-af8e2bf85d39.png">

**Desktop (please complete the following information):**
 - Operating System
 - Mac 
 - Fedora (ssh client)
 - Terminal
 - Iterm2
 - Version of Neovim
 - NVIM v0.5.0 (Fedora)
 - NVIM v0.5.0 (Mac)

**Additional context**

This is the default NvChad config, I have changed nothing. I have tried reinstalling, but it doesn't help. 

This doesn't occur outside of tmux.

**Comment by G-Rowell** [comment] 2021-08-19 15:31
Hmmm, it's 1:30am for me so I'll have to look into this tomorrow 

It's strange because the theme does set a background colour,
[eg the default bg colour](https://github.com/NvChad/NvChad/blob/main/lua/themes/onedark.lua#L4)

I can understand that's annoying, though this may be hard to hunt down what causes this we'll try!

Also, there are members more experienced with theming than I am, so maybe they'll know

**Comment by JustSage** [comment] 2021-08-19 15:33
You’re welcome to join our discord server and I’ll try to help you sort this out :)

**Comment by ashincoder** [comment] 2021-08-19 15:38
I am pretty sure it is no problem in directly opening neovim in tmux in linux. I will have to use ssh then somehow.
![2021-08-19-210807_1366x768_scrot](https://user-images.githubusercontent.com/83629316/130098650-70815303-a6db-4302-af9f-cd25418fde0c.png)

**Comment by G-Rowell** [comment] 2021-08-20 01:15
@skrapi 

Would you be able to try [another terminal multiplexer such as screen](https://linuxize.com/post/how-to-use-linux-screen/)

This would help to try narrow it down, this is certainly strange :thinking:

**Comment by ashincoder** [comment] 2021-08-20 01:33
Or @skrapi u could use kitty which has builtin terminal multiplexer. `CTRL + SHIFT + t` opens a new tab in kitty

**Comment by G-Rowell** [comment] 2021-08-20 01:41
Yeah, that's a good point

Seems like Skrapi needs to use a remote connection multiplexer, hopefully Kitty has this feature

**Comment by siduck76** [comment] 2021-08-20 04:14
check this issue 

https://github.com/NvChad/NvChad/issues/2

**Comment by siduck76** [comment] 2021-08-21 08:46
looks like duplicate of https://github.com/NvChad/NvChad/issues/2

**Closed by siduck76** 2021-08-21 08:46 UTC
