### ISSUE TITLE
Can't copy using terminal keybinds?

### ISSUE THREAD

**Issue by godspeedfw** [NvChad/NvChad#282] opened 2021-08-18 13:52 UTC
**Describe the bug**
I can't copy stuff from nvim to clipboard using terminal copy keybind. I think I was able to do this a while ago?

**To Reproduce**
1. Select text in nvim.
2. Try coping it using terminal keybinds.

**Expected behavior**
Copy to clipboard

**Desktop (please complete the following information):**
 - Operating System: arch
 - Terminal: st/alacritty
 - Version of Neovim: 0.6.0

**Comment by G-Rowell** [comment] 2021-08-18 14:00
Hi  @godspeedfw,

In the future, if you've made an Issue, please wait a while before coming to the Discord!

NvChad by default uses the system clipboard as it's primary register.

Try:
- open a file in NeoVim, type `yy` to yank/copy a line,
- go to a different application, try paste `<CNTL> + v`, this should work

**Comment by G-Rowell** [comment] 2021-08-18 14:01
It's worth noting that this also depends upon several different layers in your system,
primarily the
- terminal emulator
and the
- running terminal application

**Comment by godspeedfw** [comment] 2021-08-18 14:04
> In the future, if you've made an Issue, please wait a while before coming to the Discord!

I apologize for that.

>Try:
>
>   - open a file in NeoVim, type yy to yank/copy a line,
>   - go to a different application, try paste <CNTL> + v, this should work

This works but I wanted to know why the terminal keybindings aren't working. I believe they were working before. Also, the paste keybind works but the copy keybind doesn't.

**Comment by G-Rowell** [comment] 2021-08-18 14:06
> I apologize for that.

No problem at all friend! (We've seen a huge influx is users over the last few days :smile:)

Let me try this.....hmmm

**Comment by G-Rowell** [comment] 2021-08-18 14:09
I can confirm that my normal `<CNTL> + <SHIFT> + c` bind does not work, 
but I copy text from NeoVim the vim way with `y` *yank*ing the text.

Can't say I know off the top of my head, sorry 

Is this okay to close now?
If it's a major issue we can reopen it if need be

**Comment by godspeedfw** [comment] 2021-08-18 14:13
Ah, alright. It would have been nice if this could be fixed but I guess I'll just use `y`.

**Comment by G-Rowell** [comment] 2021-08-18 14:14
Another option is to map this yourself (presuming no conflicting mappings)

**Comment by G-Rowell** [comment] 2021-08-18 14:16
With something like

`map("v", "<C-c>", "y", opt)`

for a visual modemapping
`<CNTL> + c`
to `y`ank

**Comment by godspeedfw** [comment] 2021-08-18 14:24
How do I bind it to ctrl+shift+c ?

**Comment by G-Rowell** [comment] 2021-08-18 14:25
Change the c to a capital C

**Comment by godspeedfw** [comment] 2021-08-18 14:35
That doesn't work.

**Comment by G-Rowell** [comment] 2021-08-18 14:44
I believe it does for me?
Could you provide a little more information

**Comment by G-Rowell** [comment] 2021-08-18 14:57
I can confirm that putting 

`map("v", "<C-C>", "y", opt)`

in `mappings.lua` worked for me.

I went into visual mode by pressing `v`,
selected a few lines of text,
pressed `<CNTL> + <SHIFT> + c`,
the line were correctly yanked.

Also lowercase `c` to remove the need for `<SHIFT>` can be done with:
`map("v", "<C-c>", "y", opt)`


As I've tested these and they work I might go ahead and close this,
feel free to ask more questions but I'd heavily suggest trying `:Tutor`

**Closed by G-Rowell** 2021-08-18 14:57 UTC

**Comment by godspeedfw** [comment] 2021-08-18 15:03
`map("v", "<C-C>", "y", opt)` doesn't work for me

https://user-images.githubusercontent.com/74945202/129922305-52608677-1e30-4c69-a683-ca59f8744171.mp4

Which terminal did you test it on?

**Comment by G-Rowell** [comment] 2021-08-19 12:23
Hi Godspeed,

make you restart NeoVim each time you update the mappings,
then can you try without the mouse please 

(I don't imagine that's the issue but I want to narrow this down)

`map("v", "<C-C>", "y", opt)` 
works for me on
Debian 10, 
KDE,
Konsole 

Copy-paste tends to be something the OS/DE handles, rather than the terminal emulator.
Give this a shot again and then we'll delve into it more

**Comment by godspeedfw** [comment] 2021-08-19 12:29
I tried without the mouse and it doesn't work. 
I am using Arch, dwm, st.

**Comment by godspeedfw** [comment] 2021-08-19 12:31
I tried it on konsole and it works but not on alacritty or st.

**Comment by G-Rowell** [comment] 2021-08-19 12:41
Hmmm, it must be a setting within Alacritty & St then?

Check their mappings to see if anything is mapped to that as well,

Test a different key-map like `map("v", "<leader>", "y", opt)`  (leader is space)

**Comment by godspeedfw** [comment] 2021-08-19 13:18
They don't work either. It's okay, I'll just use the vim bindings.
