### ISSUE TITLE
statusline error

### ISSUE THREAD

**Issue by se7en-x230** [NvChad/NvChad#678] opened 2021-12-25 06:51 UTC
`packer.nvim: Error running config for feline.nvim: /home/seven/.config/nvim/lua/plugins/configs/statusline.lua:3: attempt to index field 'diagnostic' (a nil value)
packer.nvim: Error running config for nvim-lspconfig: /home/seven/.config/nvim/lua/plugins/configs/others.lua:118: attempt to index field 'diagnostic' (a nil value)`

**Comment by boppyt** [comment] 2021-12-25 06:53
Possible duplicate of #671.

**Comment by boppyt** [comment] 2021-12-25 06:54
- Update your nvchad & plugin version
- Make sure you have neovim 0.6+.

**Comment by se7en-x230** [comment] 2021-12-25 07:06
`aur/neovim-nightly-bin 0.6.0+dev+43+g02bf251bb-1 [+32 ~1.94] [Installed: 0.6.0+dev+61+g6f48c018b-1]`

Should not be the version ...
and I ran

:PadckerUpdate

**Comment by se7en-x230** [comment] 2021-12-25 07:08
If I remove everything and clone back in I get:

`packer.nvim: Error running config for nvim-lspconfig: /home/seven/.config/nvim/lua/plugins/configs/others.lua:118: attempt to index field 'diagnostic' (a nil value)
[nvim-treesitter] [0/2] Downloading...
Press ENTER or type command to continue
`

**Comment by siduck** [comment] 2021-12-25 07:17
Did you do leader uu and packersync? Packerupdate doesn't compile but we have enabled compile on sync so always do packersync

**Comment by se7en-x230** [comment] 2021-12-25 07:21
Yes PackerSync returns.
![image](https://user-images.githubusercontent.com/69777713/147379834-04fff450-bb8c-458e-b80b-2f62787504f7.png)

**Comment by siduck** [comment] 2021-12-25 07:22
> Yes PackerSync returns. ![image](https://user-images.githubusercontent.com/69777713/147379834-04fff450-bb8c-458e-b80b-2f62787504f7.png)

looks like your custom lspconfig's issue! are you using neovim 0.6?

**Comment by boppyt** [comment] 2021-12-25 07:26
`aur/neovim-nightly-bin 0.6.0+dev+43+g02bf251bb-1 [+32 ~1.94] [Installed: 0.6.0+dev+61+g6f48c018b-1]`
He's on neovim 0.6 nightly

**Comment by se7en-x230** [comment] 2021-12-25 07:29
@siduck that was it.
as I recall nightly was needed month ago.

Thanks for the fast help also @boppyt

**Closed** 2021-12-25 07:35 UTC

**Comment by peppapig450** [comment] 2021-12-27 02:02
The version is out of date because the pkgbuild for the nightly-bin hasn't been updated in 5 months, for the nightly version you can use neovim-git instead, but you would have to build it yourself

**Comment by peppapig450** [comment] 2021-12-27 03:13
This happens no matter what with nightly, I build it myself and I got errors galore. So noting in the documentation that nightly doesn't work might be smart.

**Comment by siduck** [comment] 2021-12-27 06:35
> This happens no matter what with nightly, I build it myself and I got errors galore. So maybe we should add in the documentation that nightly causes a ton of errors and is basically unusable.

yep added 

![Uploading image.png…]()
