### ISSUE TITLE
Disabling vim-matchup messes up statusline.

### ISSUE THREAD

**Issue by laraib07** [NvChad/NvChad#256] opened 2021-08-15 17:23 UTC
**Describe the bug**
if vim-matchup is disabled, statusline doesnt appear on startup. To make it appear I have to toggle nvim-tree twice.

**To Reproduce**
1. disable vim-matchup in chadrc
2. do PackerSync
3. exit and reopen vim

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System : Pop OS 21.04
 - Terminal : gnome
 - Version of Neovim : 0.5

**Additional context**

**Comment by ashincoder** [comment] 2021-08-16 00:49
yes I am able to reproduce the problem.

**Comment by ashincoder** [comment] 2021-08-16 00:49
![2021-08-16-061931_1366x768_scrot](https://user-images.githubusercontent.com/83629316/129498091-d6e0247a-24a7-4c15-bbb3-0e5249e41a0b.png)

**Comment by siduck76** [comment] 2021-08-16 00:52
Yes it happens with me too , also try opening telescope . It doesnt work either 

![image](https://user-images.githubusercontent.com/59060246/129498181-b196df93-7802-4884-a3b0-dbeeaeb08468.png)

**Comment by ashincoder** [comment] 2021-08-16 00:54
we may have to investigate

**Comment by siduck76** [comment] 2021-08-16 00:55
it breaks up plenary too BRUH 

![image](https://user-images.githubusercontent.com/59060246/129498333-11e09c23-0766-4eb8-98bb-bab249ba347d.png)

**Comment by siduck76** [comment] 2021-08-16 00:56
I wonder how could vim matchup which literally has no config can cause such severe issue :disappointed:

**Comment by ashincoder** [comment] 2021-08-16 03:02
@Akianonymus and @G-Rowell could u please check on this issue..

**Comment by Akianonymus** [comment] 2021-08-16 04:11
It is happening because  for some reason, after disabling vim matchup, plenary doesn't load, along with popup.nvim.

**Comment by G-Rowell** [comment] 2021-08-17 06:37
Is this related to my issue?

I think I have an issue related to `vim-matchup` where after multiple `:ls!`, suddenly every NeoVim config file is loaded as a hidden buffer......

**Comment by ashincoder** [comment] 2021-08-17 23:52
The issue still remains. When I disable vim_machup galaxyline doesn't open

**Comment by siduck76** [comment] 2021-08-18 02:34
> The issue still remains. When I disable vim_machup galaxyline doesn't open

Its the same with staline.nvim but other statusline do work .

**Comment by ashincoder** [comment] 2021-08-18 04:04
Lualine is great

**Comment by siduck76** [comment] 2021-08-18 04:06
> Lualine is great

If someone comes forward to replicate our current setup with lualine then we'll use it , also its og repo isnt maintained anymore :(

**Comment by ashincoder** [comment] 2021-08-18 04:06
But there is a fork so it would be better

**Comment by siduck76** [comment] 2021-08-18 04:11
> But there is a fork so it would be better

which one?

**Comment by laraib07** [comment] 2021-08-18 04:13
If you are considering to change statusline, Please consider feline. it constantly get updated and has good documentation.

**Comment by siduck76** [comment] 2021-08-18 04:32
> If you are considering to change statusline, Please consider feline. it constantly get updated and has good documentation.
> 
> Edit : And is highly customizable

I have tried that , its config looked scary xD

**Comment by siduck76** [comment] 2021-08-18 04:33
If someone can replicate our current statusline with feline or lualine then it would be nice , im working on docs today!

**Comment by laraib07** [comment] 2021-08-18 05:40
@siduck76 check this out
https://github.com/Famiu/feline.nvim#example-config

I guess you can disable statusline for some filetype and bufftype from feline config itself. No need to disable it explicitly elsewhere.

**Comment by siduck76** [comment] 2021-08-18 05:45
> @siduck76 check this out
> https://github.com/Famiu/feline.nvim#example-config
> 
> I guess you can disable statusline for some filetype and bufftype from feline config itself. No need to disable it explicitly elsewhere.

looks promising! I'll try this when the nvchad site is partially ready!

**Comment by siduck76** [comment] 2021-08-20 05:05
@ashincoder @laraib07 try disabling matcup again and check . It works for me now weirdddd :D

**Comment by laraib07** [comment] 2021-08-20 05:19
Can confirm, No issues now.

**Comment by G-Rowell** [comment] 2021-08-20 05:25
Thanks for confirming,
closing

Feel free to @ us or start a new issue

Ty :smile:

**Closed by G-Rowell** 2021-08-20 05:25 UTC
Labels: bug, help wanted

**Comment by ashincoder** [comment] 2021-08-20 07:48
> @ashincoder @laraib07 try disabling matcup again and check . It works for me now weirdddd :D

It works :D
