### ISSUE TITLE
show documentation , mappings cheatsheet internally

### ISSUE THREAD

**Issue by peppapig450** [NvChad/NvChad#582] opened 2021-10-31 23:07 UTC
**Is your feature request related to a problem? Please describe.**
No just an idea

**Describe the solution you'd like**
Maybe implement an install script to setup the config files automatically, could also be useful for #354 
could also mention where the documentation is, maybe add like a nvchad --help command? 
nvchad --mappings command? 

**Describe alternatives you've considered**
none I was just thinking

**Additional context**
This probably will be denied but I thought it was a good idea.

**Comment by siduck** [comment] 2021-11-01 00:27
we had an install script before but supporting more OS's got a lil messy and bloated. So we discarded it. But yea I'll soon add a plugin to show mappings , help etc stuff.

**Comment by peppapig450** [comment] 2021-11-01 14:39
Would it have to be in lua? I think I could write this in shell pretty easily.

**Comment by siduck** [comment] 2021-11-01 15:04
> Would it have to be in lua? I think I could write this in shell pretty easily.

the issue is , if the user adds his mappings then we want the keysheet update dynamically too! so ig this part needs to be in lua ._.

**Comment by peppapig450** [comment] 2021-11-01 18:21
cant you call shell with lua? isnt like os.execute or something

**Comment by siduck** [comment] 2021-11-01 18:22
> cant you call shell with lua? isnt like os.execute or something

Ig so but then if we're doing this with lua then shell stuff isnt needed Ig. I'll try it.

**Comment by peppapig450** [comment] 2021-11-01 23:25
Once I finish my schoolwork I will work on it in shellscipt

**Comment by peppapig450** [comment] 2021-11-02 00:58
What do you think about storing the mappings in a file and updating it when the user runs like :mappings or something

**Comment by peppapig450** [comment] 2021-11-02 00:59
I think it would be faster because you wouldn't have to loop through all the files every time you would just have to do 1.

**Comment by siduck** [comment] 2021-11-05 15:03
@peppapig450 when we'll implement it , its gonna be done in the extensions repo 

https://github.com/NvChad/extensions/issues/5 

So im closing this issue now!

**Closed by siduck** 2021-11-05 15:03 UTC
