### ISSUE TITLE
Telescope lazyload casue first running command line suggestions not working

### ISSUE THREAD

**Issue by Liampor** [NvChad/NvChad#1383] opened 2022-07-27 06:03 UTC
**Describe the bug**

If I enter nvim mode, run like `:Mason` There is no popup menu of suggestions.
But once I run one time <leader ff> to trigger telescope, every thing works.

I have searched some methods here:

e.g. add `module = "telescope"`, and put it in 

```lua
    ["nvim-telescope/telescope.nvim"] = {
      module = "telescope",
      cmd = "Telescope",
      config = function()
        require "custom.plugins.userTelescope"
      end
    },
```
in `custom/plugins/init.lua`

But the same results

**To Reproduce**
1. Go to `nvim`
2. type `:Mason`
3. No popup menu for suggestions
4. `<leader>ff` trigger telescope one time
5. type `:Mason` again, popup mene appears

**Expected behavior**
don't lazyload telescope

**Screenshots**
![image](https://user-images.githubusercontent.com/19495916/181172327-49cf01ee-0c1a-4401-a745-0457da8ef5e1.png)
After triggering telescope
![image](https://user-images.githubusercontent.com/19495916/181172252-aad8ad88-1ec0-4be7-8c79-6b009347d83f.png)

**Desktop (please complete the following information):**
 - Operating System: Windows 10
 - Terminal: Windows Terminal + Powershell 
 - Version of Neovim: 0.7.2

**Additional context**

**Comment by siduck** [comment] 2022-07-27 06:04
i hope your nvchad is upto date and do packersync then check

**Comment by siduck** [comment] 2022-07-27 06:05
https://user-images.githubusercontent.com/59060246/181173129-e053879a-3f13-4977-8d67-317560808bfe.mp4

works fine here

**Comment by Liampor** [comment] 2022-07-27 06:12
my NvChad is already up to date. Then It seems my personal configuration cause this issue

**Comment by siduck** [comment] 2022-07-27 06:14
if this works without custom config then close the issue!!

**Comment by Liampor** [comment] 2022-07-27 06:16
in my custom init.lua
there is also
```
    ["hrsh7th/nvim-cmp"] = {
      after = "friendly-snippets",
      module = "cmp",
      config = function()
         require "custom.plugins.userCmp"
      end
    },
    -- cmd line
    ['hrsh7th/cmp-cmdline'] = {
      after = 'cmp-path',
    },
```
But I couldn't understand, why after telescope triggering works well

**Comment by siduck** [comment] 2022-07-27 06:16
> in my custom init.lua there is also
> 
> ```
>     ["hrsh7th/nvim-cmp"] = {
>       after = "friendly-snippets",
>       module = "cmp",
>       config = function()
>          require "custom.plugins.userCmp"
>       end
>     },
>     -- cmd line
>     ['hrsh7th/cmp-cmdline'] = {
>       after = 'cmp-path',
>     },
> ```
> 
> But I couldn't understand, why after telescope triggering works well

show your chadrc

**Comment by siduck** [comment] 2022-07-27 06:18
maybe this is sus         require "custom.plugins.userTelescope"

**Comment by Liampor** [comment] 2022-07-27 06:19
```
M.plugins = {

   -- custom plugins
   user = require "custom.plugins",

   -- override plugins settings
   override = {
      ["kyazdani42/nvim-tree.lua"] = override.nvimtree,
      ["nvim-treesitter/nvim-treesitter"] = override.treesitter,
      ["lukas-reineke/indent-blankline.nvim"] = override.blankline,
      ["goolord/alpha-nvim"] = override.dashboard,
      ["hrsh7th/nvim-cmp"] = override.cmp,
   },
}
```
with

```
M.cmp = {
   formatting = {
      fields = { "kind", "abbr", "menu" },
      max_width = 0,
      kind_icons = {
        Class = " ",
        Color = " ",
        Constant = "ﲀ ",
        Constructor = " ",
        Enum = "練",
        EnumMember = " ",
        Event = " ",
        Field = " ",
        File = "",
        Folder = " ",
        Function = " ",
        Interface = "ﰮ ",
        Keyword = " ",
        Method = " ",
        Module = " ",
        Operator = "",
        Property = " ",
        Reference = " ",
        Snippet = " ",
        Struct = " ",
        Text = " ",
        TypeParameter = " ",
        Unit = "塞",
        Value = " ",
        Variable = " ",
      },
      source_names = {
        nvim_lsp = "(LSP)",
        treesitter = "(TS)",
        emoji = "(Emoji)",
        path = "(Path)",
        calc = "(Calc)",
        cmp_tabnine = "(Tabnine)",
        vsnip = "(Snippet)",
        luasnip = "(Snippet)",
        buffer = "(Buffer)",
        spell = "(Spell)",
        copilot="(Copilot)",
      },
      duplicates = {
        copilot = 0,
        buffer = 1,
        path = 1,
        nvim_lsp = 0,
        luasnip = 1,
      },
      duplicates_default = 0,
      format = function(entry, vim_item)
        local max_width = M.cmp.formatting.max_width
        if max_width ~= 0 and #vim_item.abbr > max_width then
          vim_item.abbr = string.sub(vim_item.abbr, 1, max_width - 1) .. "…"
        end
        if entry.source.name == "copilot" then
         vim_item.kind = "[] Copilot"
         --vim_item.kind = string.format("%s %s", "[] Copilot", vim_item.kind)
         vim_item.kind_hl_group = "CmpItemKindCopilot"
         -- return vim_item
        else
         vim_item.kind = M.cmp.formatting.kind_icons[vim_item.kind]
        end
        vim_item.menu = M.cmp.formatting.source_names[entry.source.name]
        vim_item.dup = M.cmp.formatting.duplicates[entry.source.name]
            or M.cmp.formatting.duplicates_default
        return vim_item
      end,
   },

   sources = {
      { name = "copilot", group_index = 2 },
      { name = "nvim_lsp" },
      { name = "path" },
      { name = "luasnip" },
      { name = "nvim_lua" },
      { name = "buffer" },
      { name = "spell" },
      -- { name = "calc" },
      -- { name = "emoji" },
      -- { name = "crates" },
   },
}
```

**Comment by siduck** [comment] 2022-07-27 06:20
does mason work when you dont have custom config at all?

**Comment by Liampor** [comment] 2022-07-27 06:21
> 

Yes it works

**Comment by Liampor** [comment] 2022-07-27 06:23
userTelescope.lua is here
```
local present, telescope = pcall(require, "telescope")

if not present then
   return
end

vim.g.theme_switcher_loaded = true

require("base46").load_highlight "telescope"

local options = {
   defaults = {
      vimgrep_arguments = {
         "rg",
         "--color=never",
         "--no-heading",
         "--with-filename",
         "--line-number",
         "--column",
         "--smart-case",
      },
      prompt_prefix = "   ",
      selection_caret = "  ",
      entry_prefix = "  ",
      initial_mode = "insert",
      selection_strategy = "reset",
      sorting_strategy = "ascending",
      layout_strategy = "horizontal",
      layout_config = {
         horizontal = {
            prompt_position = "top",
            preview_width = 0.55,
            results_width = 0.8,
         },
         vertical = {
            mirror = false,
         },
         width = 0.87,
         height = 0.80,
         preview_cutoff = 120,
      },
      -- not set file_sorter if you load fyz_native because fzy_native does this for you :)
      file_sorter = require("telescope.sorters").get_fuzzy_file,
      file_ignore_patterns = { "node_modules" },
      generic_sorter = require("telescope.sorters").get_generic_fuzzy_sorter,
      path_display = { "truncate" },
      winblend = 0,
      border = {},
      borderchars = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
      color_devicons = true,
      set_env = { ["COLORTERM"] = "truecolor" }, -- default = nil,
      file_previewer = require("telescope.previewers").vim_buffer_cat.new,
      grep_previewer = require("telescope.previewers").vim_buffer_vimgrep.new,
      qflist_previewer = require("telescope.previewers").vim_buffer_qflist.new,
      -- Developer configurations: Not meant for general override
      buffer_previewer_maker = require("telescope.previewers").buffer_previewer_maker,
      mappings = {
         n = { ["q"] = require("telescope.actions").close },
      },
   },

   extensions_list = { "themes", "terms", "fzf", "live_grep_args", "project", "media_files", "frecency"},
   extensions = {
        -- fzf syntax
        -- Token	Match type	Description
        -- sbtrkt	fuzzy-match	Items that match sbtrkt
        -- 'wild'	exact-match (quoted)	Items that include wild
        -- ^music	prefix-exact-match	Items that start with music
        -- .mp3$	suffix-exact-match	Items that end with .mp3
        -- !fire	inverse-exact-match	Items that do not include fire
        -- !^music	inverse-prefix-exact-match	Items that do not start with music
        -- !.mp3$	inverse-suffix-exact-match	Items that do not end with .mp3
        fzf = {
         fuzzy = true, -- false will only do exact matching
         override_generic_sorter = true, -- override the generic sorter
         override_file_sorter = true, -- override the file sorter
         case_mode = "smart_case", -- or "ignore_case" or "respect_case"
         -- the default case_mode is "smart_case"
        },

        media_files = {
        -- filetypes whitelist
        -- defaults to {"png", "jpg", "mp4", "webm", "pdf"}
         filetypes = {"png", "webp", "jpg", "jpeg", "gif", "pdf"},
         find_cmd = "rg", -- find command (defaults to `fd`)
        },

        live_grep_args = {
         auto_quoting = true, -- enable/disable auto-quoting
        },

    },
}

-- check for any override
options = require("core.utils").load_override(options, "nvim-telescope/telescope.nvim")
telescope.setup(options)

-- load extensions
pcall(function()
   for _, ext in ipairs(options.extensions_list) do
      telescope.load_extension(ext)
   end
end)

```

**Comment by tomasky** [comment] 2022-07-27 07:07
:Mason   shouldn't need  telescope.nvim , maybe not related to  telescope.nvim

**Comment by tomasky** [comment] 2022-07-27 07:18
check your `custom/plugins/init.lua`

**Comment by Liampor** [comment] 2022-07-27 07:27
> :Mason shouldn't need telescope.nvim , maybe not related to telescope.nvim

Yes It's not the mason related issue. I just use it as an example

First running :PackerStatus
```
 • Comment.nvim (not loaded)
 • LuaSnip (not loaded)
 • alpha-nvim
 • asyncrun.vim (not loaded)
 • asynctasks.vim (not loaded)
 • auto-session
 • base46
 • cmp-buffer (not loaded)
 • cmp-cmdline (not loaded)
 • cmp-nvim-lsp (not loaded)
 • cmp-nvim-lua (not loaded)
 • cmp-path (not loaded)
 • cmp_luasnip (not loaded)
 • copilot-cmp
 • copilot.lua
 • diffview.nvim (not loaded)
 • extensions
 • friendly-snippets (not loaded)
 • fzf
 • fzf.vim
 • gitsigns.nvim (not loaded)
 • indent-blankline.nvim (not loaded)
 • mason-lspconfig.nvim
 • mason.nvim (not loaded)
 • neorg (not loaded)
 • neoscroll.nvim (not loaded)
 • null-ls.nvim (not loaded)
 • nvim-autopairs (not loaded)
 • nvim-cmp (not loaded)
 • nvim-colorizer.lua (not loaded)
 • nvim-lspconfig (not loaded)
 • nvim-lspfuzzy
 • nvim-tree.lua
 • nvim-treesitter (not loaded)
 • nvim-web-devicons
 • nvterm (not loaded)
 • packer.nvim
 • playground (not loaded)
 • plenary.nvim (not loaded)
 • shade.nvim (not loaded)
 • sqlite.lua
 • suda.vim (not loaded)
 • telescope-frecency.nvim
 • telescope-fzf-native.nvim
 • telescope-live-grep-args.nvim
 • telescope-media-files.nvim
 • telescope-project.nvim
 • telescope.nvim (not loaded)
 • ui
 • undotree (not loaded)
 • vim-startuptime (not loaded)
 • vim-surround (not loaded)
 • vim-table-mode (not loaded)
 • vim-visual-multi (not loaded)
 • vista.vim (not loaded)
 • which-key.nvim
 • wildfire.vim (not loaded)
```
After triggering the telescope
```
 • Comment.nvim (not loaded)
 • LuaSnip
 • alpha-nvim
 • asyncrun.vim (not loaded)
 • asynctasks.vim (not loaded)
 • auto-session
 • base46
 • cmp-buffer
 • cmp-cmdline
 • cmp-nvim-lsp
 • cmp-nvim-lua
 • cmp-path
 • cmp_luasnip
 • copilot-cmp
 • copilot.lua
 • diffview.nvim
 • extensions
 • friendly-snippets
 • fzf
 • fzf.vim
 • gitsigns.nvim (not loaded)
 • indent-blankline.nvim (not loaded)
 • mason-lspconfig.nvim
 • mason.nvim (not loaded)
 • neorg
 • neoscroll.nvim (not loaded)
 • null-ls.nvim (not loaded)
 • nvim-autopairs
 • nvim-cmp
 • nvim-colorizer.lua (not loaded)
 • nvim-lspconfig (not loaded)
 • nvim-lspfuzzy
 • nvim-tree.lua
 • nvim-treesitter
 • nvim-web-devicons
 • nvterm (not loaded)
 • packer.nvim
 • playground (not loaded)
 • plenary.nvim
 • shade.nvim (not loaded)
 • sqlite.lua
 • suda.vim (not loaded)
 • telescope-frecency.nvim
 • telescope-fzf-native.nvim
 • telescope-live-grep-args.nvim
 • telescope-media-files.nvim
 • telescope-project.nvim
 • telescope.nvim
 • ui
 • undotree (not loaded)
 • vim-startuptime (not loaded)
 • vim-surround (not loaded)
 • vim-table-mode (not loaded)
 • vim-visual-multi (not loaded)
 • vista.vim (not loaded)
 • which-key.nvim
 • wildfire.vim (not loaded)
```

**Comment by tomasky** [comment] 2022-07-27 07:38
• mason.nvim (not loaded)

if i open nvim with alpha-nvim ,my mason.nvim was loaded.

 • mason.nvim 

so the problem is your mason.nvim not be loaded

**Comment by tomasky** [comment] 2022-07-27 07:44
you can check your `custom/plugins/init.lua`, remove some plugins and see if it works

**Comment by siduck** [comment] 2022-07-27 08:35
> > 
> 
> Yes it works

hmm then i'll be closing this, remove parts from your chadrc bit by bit and then check.

**Closed by siduck** 2022-07-27 08:35 UTC

**Comment by tomasky** [comment] 2022-07-27 08:48
@siduck  maybe should update issue template ,add some tips about update nvchad and plugins

**Comment by siduck** [comment] 2022-07-27 08:57
> @siduck maybe should update issue template ,add some tips about updating nvchad and plugins

the packersync stuff will go into the upater which @LeonHeidelbach handles, I'll add tips for debugging config

**Comment by tomasky** [comment] 2022-07-27 09:06
no i mean :  
`Please update to the latest nvchad version before asking questions`

**Comment by siduck** [comment] 2022-07-27 09:08
> no i mean : `Please update to the latest nvchad version before asking questions`

oh we should write it in issue template, idk how to do that. send a PR if you can

**Comment by tomasky** [comment] 2022-07-27 09:17
just update this file:
https://github.com/NvChad/NvChad/blob/main/.github/ISSUE_TEMPLATE/bug_report.md
