### ISSUE TITLE
cmp(?) filling up buffer with nvim commands

### ISSUE THREAD

**Issue by Multichaos** [NvChad/NvChad#926] opened 2022-04-01 14:12 UTC
**Describe the bug**
When using the base NVChad (and especially when using lsp servers like pyright or clangd) the buffer gets filled with messages making it unusable.

**To Reproduce**

1. Installed base NVChad
2. Added lsp support using online documentation for pyright and clangd.

**Expected behavior**
Only show completion window, not fill up entire buffer.

**Screenshots**
![error](https://user-images.githubusercontent.com/50079063/161280405-0bf99c62-39e2-4341-b016-030f496f55a3.png)

**Desktop (please complete the following information):**
 - Operating System
 OpenSuse Tumbleweed
 - Terminal
 Konsole
 - Version of Neovim
v0.6.1

**Additional context**
Just started using NVChad 2 days ago. Has anyone encountered this problem? I really like the project and would like to continue using it.

**Comment by siduck** [comment] 2022-04-01 14:16
dang thats very scary, can you tell me how did you produce this issue with clangd?

**Comment by Multichaos** [comment] 2022-04-01 14:22
> dang thats very scary, can you tell me how did you produce this issue with clangd?

I only added clangd to the list of lspconfigs I wanted to use in my custom/plugins/lspconfig.lua file and opened a cpp file (note: I got random things like this when starting NVChad without custom configurations.

![error2](https://user-images.githubusercontent.com/50079063/161282588-56fbb7d4-4b3f-4313-847f-16a8a3630426.png)

**Comment by siduck** [comment] 2022-04-01 14:26
weird , i dont get that error 

![image](https://user-images.githubusercontent.com/59060246/161283468-554445ac-70ec-4e07-8063-74fdff11ead4.png)

**Comment by siduck** [comment] 2022-04-01 14:27
can u try alacritty and check the issue?

**Comment by Multichaos** [comment] 2022-04-01 14:31
I can confirm that apparently konsole is causing the issue. Alacritty worked great.

**Comment by siduck** [comment] 2022-04-01 14:55
oh no! boohoo for konsole!! so other terminals work fine?

**Comment by Multichaos** [comment] 2022-04-01 15:00
Alacritty worked fine, I'll make sure to try some others and see if they look okay.

**Comment by siduck** [comment] 2022-04-05 02:30
does this occur with vanilla nvim lsp+cmp config?

**Comment by Multichaos** [comment] 2022-04-05 13:37
No. Before coming over to NvChad, I've had my own setups trying both cmp and coq. I never had this issue on any terminal. Granted, I never did really any advanced config, Just used the basic setup they have on they're github.

**Comment by ericwq** [comment] 2022-04-11 16:19
iTerm2 is the worst (multi line hints with NVIM). alacritty and kitty is better (one line hint with NVIM). So I guess that is related with escape sequence process. It's not NvChad issue.

**Comment by siduck** [comment] 2022-04-11 16:39
> iTerm2 is the worst (multi line hints with NVIM). alacritty and kitty is better (one line hint with NVIM). So I guess that is related with escape sequence process. It's not NvChad issue.

ohh didnt know! you could check wezterm or maybe warp.dev

**Comment by ericwq** [comment] 2022-04-12 00:42
wezterm is the same as alacritty and kitty. (single line hint with NVIM). See below. Now I suspect who send this sequence? LSP or cmp?
<img width="683" alt="Screen Shot 2022-04-12 at 08 38 27" src="https://user-images.githubusercontent.com/1501146/162855620-5a9150e4-8fe5-41db-8087-3b3f0402424d.png">
.

**Comment by ericwq** [comment] 2022-04-12 01:20
It's not a LSP/cmp related problem. The first time I tried to open directory in nvim_tree. It happens again. 
<img width="926" alt="Screen Shot 2022-04-12 at 09 16 00" src="https://user-images.githubusercontent.com/1501146/162859229-e21f9ba4-88aa-483f-846c-927b1a7d8274.png">

**Comment by siduck** [comment] 2022-04-12 04:31
> @siduck can u figure out what this list means?
> 
> ```
> packerInit.lua (~/.config/nvim/lua/plugins) - NVIM
> autocmds.lua (~/.config/nvim/lua/core) - NVIM
> options.lua (~/.config/nvim/lua/core) - NVIM
> utils.lua (~/.config/nvim/lua/core) - NVIM
> others.lua (~/.config/nvim/lua/plugins/configs) - NVIM
> lspkind_icons.lua (~/.config/nvim/lua/plugins/configs) - NVIM
> icons.lua (~/.config/nvim/lua/plugins/configs) - NVIM
> bufferline.lua (~/.config/nvim/lua/plugins/configs) - NVIM
> chadrc.lua (~/.config/nvim/examples) - NVIM
> init.lua (~/.config/nvim/lua/plugins) - NVIM
> treesitter.lua (~/.config/nvim/lua/plugins/configs) - NVIM
> nvimtree.lua (~/.config/nvim/lua/plugins/configs) - NVIM
> highlights.lua (~/.config/nvim/lua/colors) - NVIM
> init.lua (~/.config/nvim/lua/colors) - NVIM
> alpha.lua (~/.config/nvim/lua/plugins/configs) - NVIM
> mappings.lua (~/.config/nvim/lua/core) - NVIM
> statusline.lua (~/.config/nvim/lua/plugins/configs) - NVIM
> lspconfig.lua (~/.config/nvim/lua/plugins/configs) - NVIM
> telescope.lua (~/.config/nvim/lua/plugins/configs) - NVIM
> default_config.lua (~/.config/nvim/lua/core) - NVIM
> init.lua (~/.config/nvim/examples) - NVIM
> cmp.lua (~/.config/nvim/lua/plugins/configs) - NVIM
> ```

I think its the loading sequence of the plugins/modules :thinking:

**Comment by ericwq** [comment] 2022-04-12 07:23
- delete the ~/.config/nvim/example directory. GOAL：eliminate interference factor
- disable all the `g.nvim_tree_*`  variable in ~/.config/nvim/lua/plugins/configs/nvimtree.lua: GOAL: [nvim_tree](https://github.com/kyazdani42/nvim-tree.lua) remove some global variables. I just disable them all.
- vi ~/.config/nvim/init.lua

The following message appears on the screen, after the `Loading workspace...` (at the bottom) finished.
```
telescope.lua           (~/.config/nvim/lua/plugins/configs) - NVIM
init.lua                (~/.config/nvim/lua/colors) - NVIM
autocmds.lua            (~/.config/nvim/lua/core) - NVIM
default_config.lua      (~/.config/nvim/lua/core) - NVIM
bufferline.lua          (~/.config/nvim/lua/plugins/configs) - NVIM
options.lua             (~/.config/nvim/lua/core) - NVIM
utils.lua               (~/.config/nvim/lua/core) - NVIM
mappings.lua            (~/.config/nvim/lua/core) - NVIM
cmp.lua                 (~/.config/nvim/lua/plugins/configs) - NVIM
statusline.lua          (~/.config/nvim/lua/plugins/configs) - NVIM
lspkind_icons.lua       (~/.config/nvim/lua/plugins/configs) - NVIM
init.lua                (~/.config/nvim/lua/plugins) - NVIM
treesitter.lua          (~/.config/nvim/lua/plugins/configs) - NVIM
nvimtree.lua            (~/.config/nvim/lua/plugins/configs) - NVIM
highlights.lua          (~/.config/nvim/lua/colors) - NVIM
lspconfig.lua           (~/.config/nvim/lua/plugins/configs) - NVIM
others.lua              (~/.config/nvim/lua/plugins/configs) - NVIM
packerInit.lua          (~/.config/nvim/lua/plugins) - NVIM
alpha.lua               (~/.config/nvim/lua/plugins/configs) - NVIM
icons.lua               (~/.config/nvim/lua/plugins/configs) - NVIM
```

**Comment by ericwq** [comment] 2022-04-12 07:24
> * delete the ~/.config/nvim/example directory. GOAL：eliminate interference factor
> * disable all the `g.nvim_tree_*`  variable in ~/.config/nvim/lua/plugins/configs/nvimtree.lua: GOAL: [nvim_tree](https://github.com/kyazdani42/nvim-tree.lua) remove some global variables. I just disable them all.
> * vi ~/.config/nvim/init.lua
> 
> The following message appears on the screen, after the `Loading workspace...` (at the bottom) finished.
> 
> ```
> telescope.lua           (~/.config/nvim/lua/plugins/configs) - NVIM
> init.lua                (~/.config/nvim/lua/colors) - NVIM
> autocmds.lua            (~/.config/nvim/lua/core) - NVIM
> default_config.lua      (~/.config/nvim/lua/core) - NVIM
> bufferline.lua          (~/.config/nvim/lua/plugins/configs) - NVIM
> options.lua             (~/.config/nvim/lua/core) - NVIM
> utils.lua               (~/.config/nvim/lua/core) - NVIM
> mappings.lua            (~/.config/nvim/lua/core) - NVIM
> cmp.lua                 (~/.config/nvim/lua/plugins/configs) - NVIM
> statusline.lua          (~/.config/nvim/lua/plugins/configs) - NVIM
> lspkind_icons.lua       (~/.config/nvim/lua/plugins/configs) - NVIM
> init.lua                (~/.config/nvim/lua/plugins) - NVIM
> treesitter.lua          (~/.config/nvim/lua/plugins/configs) - NVIM
> nvimtree.lua            (~/.config/nvim/lua/plugins/configs) - NVIM
> highlights.lua          (~/.config/nvim/lua/colors) - NVIM
> lspconfig.lua           (~/.config/nvim/lua/plugins/configs) - NVIM
> others.lua              (~/.config/nvim/lua/plugins/configs) - NVIM
> packerInit.lua          (~/.config/nvim/lua/plugins) - NVIM
> alpha.lua               (~/.config/nvim/lua/plugins/configs) - NVIM
> icons.lua               (~/.config/nvim/lua/plugins/configs) - NVIM
> ```

There is no `custom` directory?

**Comment by ericwq** [comment] 2022-04-25 07:33
After several tests. I found that `ncurses` library might be the cause of the problem.

**Comment by siduck** [comment] 2022-04-25 07:38
:worried:

**Comment by ericwq** [comment] 2022-04-25 08:21
@Multichaos can you verify it?

**Comment by siduck** [comment] 2022-05-15 02:14
> The work-around is obvious: change TERM to other value: `export TERM=kitty` or `export TERM=alacritty` works fine for me.
> 
> Lucky, the `ncurses` contains `terminfo entry` for `kitty` and `alacritty`.
> 
> `TERM=xterm-color` also works. `xterm` and `xterm-256color` doesn't work.

closing this as it seems like a terminal issue!

**Closed by siduck** 2022-05-15 02:14 UTC
