### ISSUE TITLE
Wrong indentation with html files

### ISSUE THREAD

**Issue by PoSayDone** [NvChad/NvChad#1587] opened 2022-09-22 13:13 UTC
Nvim adds tabs when it doesn't needed

1. Open any html file
2. Just start writing code

https://user-images.githubusercontent.com/29358657/191756401-21b99fdd-2ebe-439a-9851-49f6f6f4ae69.mp4

**Comment by siduck** [comment] 2022-09-22 14:37
it is normal, look how thick is the space between your indentlines?

![image](https://user-images.githubusercontent.com/59060246/191776518-cd7d853c-7182-4578-bb0a-3b8b07c89d77.png)

**Comment by siduck** [comment] 2022-09-22 14:38
https://user-images.githubusercontent.com/59060246/191776723-854fd741-0ad6-45db-a68b-24198838edd0.mp4

**Comment by PoSayDone** [comment] 2022-09-23 06:26
> it is normal, look how thick is the space between your indentlines?
> 
> ![image](https://user-images.githubusercontent.com/59060246/191776518-cd7d853c-7182-4578-bb0a-3b8b07c89d77.png)
> 
> 

Yep, I've set bigger indents

**Comment by PoSayDone** [comment] 2022-09-23 06:27
> 
> https://user-images.githubusercontent.com/59060246/191776723-854fd741-0ad6-45db-a68b-24198838edd0.mp4
> 
> 

:( would try to set default indents when would be at home

**Comment by PoSayDone** [comment] 2022-09-24 11:50
Nah, still acting the same.
https://user-images.githubusercontent.com/29358657/192096442-8781d956-44e8-4c4f-8aab-9d63bb8d72d1.mp4

**Comment by PoSayDone** [comment] 2022-09-24 11:56
Clean install with config from your dots, acting the same

https://user-images.githubusercontent.com/29358657/192096678-1e795637-4475-4e92-becd-379a199726da.mp4

**Comment by siduck** [comment] 2022-09-24 12:50
why is your cursor shifting towards left? are you manually moving it

**Comment by PoSayDone** [comment] 2022-09-25 09:12
> why is your cursor shifting towards left? are you manually moving it

Nope it doing it by himself

**Comment by siduck** [comment] 2022-09-25 10:24
i'm unable to reproduce this!

**Comment by PoSayDone** [comment] 2022-09-25 10:58
> i'm unable to reproduce this!

Really strange, I am using same nvim config, same term, really strange(

**Comment by PoSayDone** [comment] 2022-09-25 11:13
Cleared .local/share/nvim, now everything works fine

**Comment by PoSayDone** [comment] 2022-09-25 11:26
I found why that was happening, I've uninstalled TreeSitter for html and everything now works as expected

**Comment by siduck** [comment] 2022-09-25 11:27
@PoSayDone but

**Comment by PoSayDone** [comment] 2022-09-25 11:36
> @PoSayDone but the syntax highlighting?  isnt that needed

nah, syntax highlight still works

**Comment by siduck** [comment] 2022-09-25 12:08
oh nvm i misread

**Closed by siduck** 2022-09-25 12:08 UTC
