### ISSUE TITLE
Unable to open different folder via nvim command

### ISSUE THREAD

**Issue by chakrihacker** [NvChad/NvChad#316] opened 2021-08-21 04:33 UTC
**Describe the bug**

`nvim /path/to/directory`
 should open the specified path. which is is not happening with nvchad

**To Reproduce**
Expalined above

**Expected behavior**
Should open specified path instead of current working directory

**Desktop (please complete the following information):**
 - Operating System (MacOs)
 - Terminal (iTerm 2)
 - Version of Neovim(0.5)

**Comment by G-Rowell** [comment] 2021-08-21 04:36
Yup!

That's totally an issue we have right now,
I've been meaning to fix this, but myself and several of the core team have uni exams on in the next few days.

I'm adding this to our tracking list issue.

Apologies for that!

(it's likely caused by disabling the in-built `netrw`, I just use `<CNTL> + n` in the meantime for NvimTree

**Comment by siduck76** [comment] 2021-08-21 04:42
@chakrihacker remove this from the pluginList.lua file  and do :PackerSync
 
 
![image](https://user-images.githubusercontent.com/59060246/130310695-4d07ab85-c545-46e4-b7ab-4ccf50871e1a.png)

**Comment by siduck76** [comment] 2021-08-21 04:42
nvimtree is lazy loaded by default so this happens.

**Comment by G-Rowell** [comment] 2021-08-21 04:45
Note that this will be overwritten if you update,
we're working on that too!

**Comment by siduck76** [comment] 2021-08-21 08:28
@chakrihacker it must be fixed now.

**Comment by chakrihacker** [comment] 2021-08-21 08:47
Awesome 😎

**Comment by primeapple** [comment] 2022-04-14 16:32
Hey, I'm unsure if I should open a new issue for this, but could we please revisit this?
The autocommand (line 3, `autocmds.lua`) is commented out. Even if I uncomment it, it does not work. I would still like to keep NvimTree lazyloaded, so is there a way to make it work again?

**Closed** 2022-04-14 17:00 UTC
