### ISSUE TITLE
In normal mode `l` typed with 1 sec lag

### ISSUE THREAD

**Issue by Mr-Jack82** [NvChad/NvChad#1123] opened 2022-05-24 09:37 UTC
**Describe the bug**
When I’m in normal mode navigating through file `h, j, k` work fine but when I press `l` there are a 1 sec lag. I find out that is somehow related with **which-key**. Actually, when I uninstall **which-key** or comment out custom maps file that behavior is disappeared. At the same time, there are no errors in the file itself, since I wrote it according to the instructions. 

**Expected behavior**
Instant input with no time lag

**Desktop (please complete the following information):**
 - Operating System
 - Arch Linux
 - Terminal
 - ST
 - Version of Neovim
- Nvim v0.7.0
**Additional context**
My mappings.lua:
```
local M = {}

M.disabled = {
  n = {
    -- Disable some of the default mappings
    ["<C-s>"] = "",
    ["<C-c>"] = "",
    ["<leader>n"] = "",
    ["<leader>rn"] = "",
    ["<C-n>"] = "", -- to disable 'Ctrl + n' in nvimtree
    ["<S-b>"] = "",
  }
}

M.general = {

  n = {
    -- Telescope
    ["<leader>cc"] = {"<cmd> Telescope <CR>", "Toggle telescope"},

    -- Save
    ["<leader>,"] = {"<cmd> w <CR>", "Quick save"},

    -- Little text editing improvements
    ["'"] = {",", "Inline search backward"},
    ["J"] = {"mzJ`z", "String concatenation"},
    ["p"] = {"p`]", "Edit fix"},

    -- Search helpers
    ["n"] = {"nzzzv", "Center text on search"},
    ["N"] = {"Nzzzv", "Center text on search"},

    -- Fugitive
    ["<leader>gs"] = {"<cmd> Git <CR>", "Fugitive"},
    ["<leader>gb"] = {"<cmd> Git blame <CR>", "Fugitive"},
    ["leader>gh"] = {"<cmd> diffget //2 <CR>", "Fugitive"},
    ["<leader>gl"] = {"<cmd> diffget //3 <CR>", "Fugitive"},
  },

  x = {
    -- Move test
    ["K"] = {"<cmd> move '<-2<CR>gv=gv", "  Move text down"},
    ["J"] = {"<cmd> move '>+1<CR>gv=gv", "  Move text up"},
  },

  v = {
    ["v"] = {"<Esc>y$gv", "Copy visual line "},
    ["y"] = {"y`]", "Edit fix"},
    ["p"] = {"p`]", "Edit fix"},
  },

}

M.nvimtree = {
  n = {
    ["<leader>n"] = {"<cmd> NvimTreeToggle <CR>", "Toggle nvimtree"},
    ["<leader>e"] = {"<cmd> NvimTreeFocus <CR>", "Focus nvimtree"},
  },
}

return M

```

**Comment by siduck** [comment] 2022-05-24 10:32
oh my bad, btw i dont face that issue as well!

**Comment by siduck** [comment] 2022-05-24 10:35
can you show a video?

**Comment by Mr-Jack82** [comment] 2022-05-24 10:51
https://user-images.githubusercontent.com/7306093/170018191-f3657c42-6559-4971-97d2-f6887ae682a7.mp4

**Comment by LeonHeidelbach** [comment] 2022-05-24 11:13
@siduck @Mr-Jack82 no I do not have this issue at all. My `l` key is very responsive. You might have a mapping like `ls` in your custom mapping i.e. a map that has the `l` key as the first part of the key binding. In that case which-key adds a little delay to the first key in order to prompt you with the key map popup (if you have that enabled). This is just a guess though. It might also be a custom plugin that you installed, however this is not an issue with NvChad itself but rather one that has to do with your custom configuration.

**Comment by siduck** [comment] 2022-05-24 11:14
I agree, @Mr-Jack82 does this occur with vanilla nvchad?

**Comment by LeonHeidelbach** [comment] 2022-05-24 11:15
@Mr-Jack82 you can even see that you have something bound to the `l` key because the letter shows up in the bottom right corner of your buffer. That only happens if the key is the first part of a binding.

**Comment by tomasky** [comment] 2022-05-24 11:38
I reproduced this,  default nvchad and the following  mappings config

```lua
local M = {}

M.disabled = {
  n = {
    -- Disable some of the default mappings
    ["<C-s>"] = "",
    ["<C-c>"] = "",
    ["<leader>n"] = "",
    ["<leader>rn"] = "",
    ["<C-n>"] = "", -- to disable 'Ctrl + n' in nvimtree
    ["<S-b>"] = "",
  }
}

M.general = {

  n = {
    -- Telescope
    ["<leader>cc"] = {"<cmd> Telescope <CR>", "Toggle telescope"},

    -- Save
    ["<leader>,"] = {"<cmd> w <CR>", "Quick save"},

    -- Little text editing improvements
    ["'"] = {",", "Inline search backward"},
    ["J"] = {"mzJ`z", "String concatenation"},
    ["p"] = {"p`]", "Edit fix"},

    -- Search helpers
    ["n"] = {"nzzzv", "Center text on search"},
    ["N"] = {"Nzzzv", "Center text on search"},

    -- Fugitive
    ["<leader>gs"] = {"<cmd> Git <CR>", "Fugitive"},
    ["<leader>gb"] = {"<cmd> Git blame <CR>", "Fugitive"},
    ["leader>gh"] = {"<cmd> diffget //2 <CR>", "Fugitive"},
    ["<leader>gl"] = {"<cmd> diffget //3 <CR>", "Fugitive"},
  },

  x = {
    -- Move test
    ["K"] = {"<cmd> move '<-2<CR>gv=gv", "  Move text down"},
    ["J"] = {"<cmd> move '>+1<CR>gv=gv", "  Move text up"},
  },

  v = {
    ["v"] = {"<Esc>y$gv", "Copy visual line "},
    ["y"] = {"y`]", "Edit fix"},
    ["p"] = {"p`]", "Edit fix"},
  },

}

M.nvimtree = {
  n = {
    ["<leader>n"] = {"<cmd> NvimTreeToggle <CR>", "Toggle nvimtree"},
    ["<leader>e"] = {"<cmd> NvimTreeFocus <CR>", "Focus nvimtree"},
  },
}

return M
```

**Comment by siduck** [comment] 2022-05-24 11:47
https://user-images.githubusercontent.com/59060246/170027608-8839684b-13b0-4cce-b8e9-e2f1a507b9b9.mp4


cant reproduce this at all

**Comment by siduck** [comment] 2022-05-24 11:48
we dont even  have a mapping starting from l, idk how is this possible :thinking:

**Comment by tomasky** [comment] 2022-05-24 12:04
If i remove the mappings ,the problem gone, i dont know why
```lua
   -- Fugitive
    ["<leader>gs"] = {"<cmd> Git <CR>", "Fugitive"},
    ["<leader>gb"] = {"<cmd> Git blame <CR>", "Fugitive"},
    ["leader>gh"] = {"<cmd> diffget //2 <CR>", "Fugitive"},
    ["<leader>gl"] = {"<cmd> diffget //3 <CR>", "Fugitive"},
```

**Comment by siduck** [comment] 2022-05-24 12:05
its <leader>gh and not leader>gh

**Comment by tomasky** [comment] 2022-05-24 12:05
So ,i found the problem

**Comment by siduck** [comment] 2022-05-24 12:05
> try finding the plugin that triggers `i` or uses it

no plugin does

**Comment by siduck** [comment] 2022-05-24 12:06
@tomasky its fixed now? so I can close the issue :laughing: , gotta keep the issue count to 0

**Comment by siduck** [comment] 2022-05-24 12:07
tested it locally and that was the issue. closing this now

**Comment by siduck** [comment] 2022-05-24 12:08
Bois before making issue, please check if it occurs with vanilla config or no, if no then dont make the issue, ask it on the discord/matrix server or telegram group

**Closed by siduck** 2022-05-24 12:07 UTC

**Comment by Mr-Jack82** [comment] 2022-05-24 12:09
Yes, somehow fugitive mappings related to this issue. Issue closed. Also, big thanks for quick response

**Comment by siduck** [comment] 2022-05-24 12:56
> @siduck , `require "custom"` appears in example/chadrc.lua file

ooh oops, i'll remove it in next commit

**Comment by LeonHeidelbach** [comment] 2022-05-24 13:40
> If i remove the mappings ,the problem gone, i dont know why
> 
> ```lua
> 
>    -- Fugitive
> 
>     ["<leader>gs"] = {"<cmd> Git <CR>", "Fugitive"},
> 
>     ["<leader>gb"] = {"<cmd> Git blame <CR>", "Fugitive"},
> 
>     ["leader>gh"] = {"<cmd> diffget //2 <CR>", "Fugitive"},
> 
>     ["<leader>gl"] = {"<cmd> diffget //3 <CR>", "Fugitive"},
> 
> ```

Haha nice one 😆 @Mr-Jack82 you literally registered a huge map starting with `l` and going all the way through to `h` with all characters i.e "eader>g" in between just because of the missing "<" at the beginning. For this fugitive action. Nice catch @siduck, that was a subtle one 👍

**Comment by Mr-Jack82** [comment] 2022-05-24 13:50
Thanks I already find it out, all because of my inattention 😁
