### ISSUE TITLE
How to restore default tab behaviour

### ISSUE THREAD

**Issue by djpiper28** [NvChad/NvChad#1273] opened 2022-06-26 19:38 UTC
the current tabs are funky. I want :tabnew to open a new tab to the right. Then gt, gT to go between them. the tab system in the base config is not like that of default vim and is scaring me. please help me.

**Comment by siduck** [comment] 2022-06-27 00:12
switching tabs is the same as default vim. Only difference is that tab will show its only buffers in the "bufferline" so whats the whole fuss about?

**Comment by siduck** [comment] 2022-06-27 00:15
so this is a duplicate of this https://github.com/NvChad/NvChad/issues/1274. Will add an option today so you could use other bufferline plugins

**Closed** 2022-06-27 00:16 UTC
