### ISSUE TITLE
i want to convert keybinds from lua to viml how can i convert the terminal keybinds

### ISSUE THREAD

**Issue by imSafdarAwan** [NvChad/NvChad#402] opened 2021-08-29 05:59 UTC
map("n", "<leader>tx", ":execute 15 .. 'new +terminal' | let b:term_type = 'hori' | startinsert <CR>")
map("n", "<leader>tv", ":execute 'vnew +terminal' | let b:term_type = 'vert' | startinsert <CR>")
map("n", "<leader>tt", ":execute 'terminal' | let b:term_type = 'wind' | startinsert <CR>")

how can i write these commands in vimL

**Comment by G-Rowell** [comment] 2021-08-29 06:17
Can I ask why you would want to convert them from Lua to VimL?

**Comment by G-Rowell** [comment] 2021-08-29 06:32
And I might close this issue,
as one could simply Google `how to write autocommands in VimL`

A Google search is very easy: https://www.google.com/search?q=how+to+write+autocommands+in+viml

**Closed by G-Rowell** 2021-08-29 06:32 UTC

**Comment by imSafdarAwan** [comment] 2021-08-29 06:42
> Can I ask why you would want to convert them from Lua to VimL?

because wri

> Can I ask why you would want to convert them from Lua to VimL?

because writing mappings in vimL is easeier than the writing them in lua and also if you are looking at the old reference of mappings they are written in the VimL

**Comment by G-Rowell** [comment] 2021-08-29 06:45
I don't understand what the issue is,

`vim.api.nvim_set_keymap(mode, lhs, rhs, options)` just is a Lua api command, which takes VimL as it's argument,
so all the tutorials and references out there are still relevant.


IE. when using `vim.api.nvim_set_keymap(mode, lhs, rhs, options)` `RHS is already VimL`

**Comment by G-Rowell** [comment] 2021-08-29 06:50
> map("n", "tx", ":execute 15 .. 'new +terminal' | let b:term_type = 'hori' | startinsert ")
> map("n", "tv", ":execute 'vnew +terminal' | let b:term_type = 'vert' | startinsert ")
> map("n", "tt", ":execute 'terminal' | let b:term_type = 'wind' | startinsert ")
> 
> how can i write these commands in vimL

These commands are Lua `vim.api` functions to execute VimL mappings

Consider reading the docs: https://neovim.io/doc/user/api.html#nvim_set_keymap()
