### ISSUE TITLE
installer: Error running config for nvim-lspconfig

### ISSUE THREAD

**Issue by pcroland** [NvChad/NvChad#710] opened 2022-01-05 21:00 UTC
**Describe the bug**
Installation fails.

**To Reproduce**
```sh
git clone https://github.com/NvChad/NvChad ~/.config/nvim
nvim +'hi NormalFloat guibg=#1e222a' +PackerSync
```
**Screenshots**
![img](https://i.kek.sh/AUjgG8q3y83.png)

**Desktop (please complete the following information):**
 - Win 10 WSL
 - wsltty
 - NVIM v0.6.0-dev+275-gafdc9e615

**Comment by boppyt** [comment] 2022-01-06 00:28
Possible duplicate of #678.
NvChad requires 0.6.1 minimum.

**Closed** 2022-01-17 15:44 UTC
