### ISSUE TITLE
chadrc.lua not applied until override.lua is manually changed

### ISSUE THREAD

**Issue by jrozhon** [NvChad/NvChad#1201] opened 2022-06-13 11:29 UTC
**Describe the bug**
I am trying to automate nvim installation. Whenever I issue the following commands to make "a clean install" of nvchad, my lua/custom/chadrc.lua configuration is ignored until I manually modify the file or the file it links to.

**To Reproduce**
Clean install by this sequence:
```
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim
rm -rf ~/.cache/nvim
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1; nvim
ln -s ~/dotfiles/nvim/custom ~/.config/nvim/lua/custom
touch -a -m ~/dotfiles/nvim/custom/override.lua
```
Then when I run nvim, the configuration from chadrc.lua is not applied and custom modules are not installed.

**Expected behavior**
A complete working configuration.

**Screenshots**
See video in attachment.

**Desktop (please complete the following information):**
 - Ubuntu 22.04
 - Alacritty 0.11
 - Neovim 0.8.0-dev

**Additional context**

https://user-images.githubusercontent.com/12800857/173343982-98188f14-7701-45ce-b291-07daf1085a0c.mp4

**Comment by tomasky** [comment] 2022-06-13 12:50
try this:

```shell
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim
rm -rf ~/.cache/nvim
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
ln -s ~/dotfiles/nvim/custom ~/.config/nvim/lua/custom
touch -a -m ~/dotfiles/nvim/custom/override.lua
nvim
```

**Comment by tomasky** [comment] 2022-06-13 14:05
Why this, maybe this, i dont known ,you can remove this to test it
```bash
touch -a -m ~/dotfiles/nvim/custom/override.lua
```

**Comment by jrozhon** [comment] 2022-06-13 14:08
Yea, this is only to "simulate" the file change, but this does not work either. I literally have to save the chadrc.lua or override.lua for the changes to take effect.

**Comment by tomasky** [comment] 2022-06-13 14:29
i canot reproduce this ,my custom plugins are installed correctly without `PackerSync`,maybe you can provide your configs,then i can test it.

**Comment by jrozhon** [comment] 2022-06-13 14:43
Thank you for your effort. Configs are attached. No changes to nvchad core were made
[custom.tar.gz](https://github.com/NvChad/NvChad/files/8892014/custom.tar.gz)
.

**Comment by tomasky** [comment] 2022-06-13 15:30
The problem maybe  in `custom/override.lua` file, these plugins are lazy loaded
```lua
local luasnip = require("luasnip")
local cmp = require("cmp")
```

**Comment by jrozhon** [comment] 2022-06-13 15:37
I tie both to VimEnter event, but this is done by the custom/plugins/init.lua, which is imported by chadrc.lua, but not executed at all. Is there a way to change the packer load attributes for a module before the chadrc.lua is executed?

**Comment by jrozhon** [comment] 2022-06-13 15:51
Sure, that is what I did...or at least I hope so, but it did not work:
custom/chadrc.lua
`M.plugins = {
  user = require("custom.plugins"),
...`
and custom/plugins/init.lua
`return {
  -- force cmp to be loaded after vimenter to allow for
  -- seamless usage of cmdline
  ["hrsh7th/nvim-cmp"] = {
    event = "VimEnter",
  },
  ['L3MON4D3/LuaSnip'] = {
    event = "VimEnter",
  },
...
`

**Comment by tomasky** [comment] 2022-06-13 16:25
Just like this, no need to config plugin/init.lua

```lua
-- custom/chadrc.lua
    ["hrsh7th/nvim-cmp"] = override.cmp(),

```


```lua
-- custom/override.lua
local M = {}

M.indentblankline = {
  show_end_of_line = true,
  space_char_blankline = " ",
  show_current_context = true,
  show_current_context_start = true,
}

M.cmp = function() 
local present, cmp = pcall(require, "cmp")
if not present then
   return {}
end
return {
   mapping = {
      ["<C-p>"] = cmp.mapping.select_prev_item(),
      ["<C-n>"] = cmp.mapping.select_next_item(),
      ["<C-d>"] = cmp.mapping.scroll_docs(-4),
      ["<C-f>"] = cmp.mapping.scroll_docs(4),
      ["<C-Space>"] = cmp.mapping.complete(),
      ["<C-e>"] = cmp.mapping.close(),
      ["<CR>"] = cmp.mapping.confirm {
         behavior = cmp.ConfirmBehavior.Insert,
         select = true,
      },
      ["<Tab>"] = cmp.mapping(function(fallback)
         if cmp.visible() then
            cmp.select_next_item()
         elseif require("luasnip").expand_or_jumpable() then
            vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>luasnip-expand-or-jump", true, true, true), "")
         else
            fallback()
         end
      end, {
         "i",
         "s",
      }),
      ["<S-Tab>"] = cmp.mapping(function(fallback)
         if cmp.visible() then
            cmp.select_prev_item()
         elseif require("luasnip").jumpable(-1) then
            vim.fn.feedkeys(vim.api.nvim_replace_termcodes("<Plug>luasnip-jump-prev", true, true, true), "")
         else
            fallback()
         end
      end, {
         "i",
         "s",
      }),
   },
   sources = {
      { name = "luasnip" },
      { name = "nvim_lsp" },
      { name = "buffer" },
      { name = "nvim_lua" },
      { name = "path" },
   },
} 
end

return M

```

**Comment by siduck** [comment] 2022-06-13 16:26
@jrozhon reproduce this error with a minimal chadrc config

**Comment by jrozhon** [comment] 2022-06-13 16:35
@tomasky no change, sorry.
@siduck could you please be more specific? What do you consider as minimal chadrc? Just an empty M table?
Thank you both guys, for your time and effort.

**Comment by jrozhon** [comment] 2022-06-13 17:10
Have tried to comment block after block from chadrc to get the minimal config that would cause an error, but miraculously no such error appeared. To be honest, I dont have a slightest clue what just happened, but the config seems to be working fine now. At least for last couple of attempts.
Thank you both, J

**Comment by siduck** [comment] 2022-06-13 17:11
@jrozhon try commenting each table in your chadrc and see the change, that'd help ig ( dont forget to recompile i.e packercompile )

**Comment by tomasky** [comment] 2022-06-14 03:34
@jrozhon ,try this, it works in my container
```lua
local M = {}


M.indentblankline = {
  show_end_of_line = true,
  space_char_blankline = " ",
  show_current_context = true,
  show_current_context_start = true,
}

M.cmp = function() 
local present, cmp = pcall(require, "cmp")

if not present then
   return {}
end
local luasnip = require("luasnip")　 -- load after cmp 
return {
  mapping = {
    ['<C-p>'] = cmp.mapping.select_prev_item(),
    ['<C-n>'] = cmp.mapping.select_next_item(),
    ['<C-d>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm {
      behavior = cmp.ConfirmBehavior.Insert,
      select = false,
    },
    ['<Tab>'] = function(fallback)
      if vim.fn.pumvisible() == 1 then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<C-n>', true, true, true), 'n')
      elseif luasnip.expand_or_jumpable() then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<Plug>luasnip-expand-or-jump', true, true, true), '')
      else
        fallback()
      end
    end,
    ['<S-Tab>'] = function(fallback)
      if vim.fn.pumvisible() == 1 then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<C-p>', true, true, true), 'n')
      elseif luasnip.jumpable(-1) then
        vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<Plug>luasnip-jump-prev', true, true, true), '')
      else
        fallback()
      end
    end,
  },
  sources = {
    { name = "nvim_lsp" },
    { name = "luasnip" },
    { name = "treesitter" },
    { name = "buffer" },
    { name = "nvim_lua" },
    { name = "path" },
    { name = "nvim_lsp_signature_help" },
    -- { name = "nvim_lsp_document_symbol" },
  },
} 
end
return M
```

**Comment by gmartsenkov** [comment] 2022-06-14 15:39
Okay, if i remove my [overrides](https://github.com/gmartsenkov/nvim/blob/93fd7bac329157858d6da9aaaf7b1cbfc3e74765/chadrc.lua#L12) it loads fine. I suppose it has something to do with lazy loading 🤔 I'm pretty new to nvim config and am struggling to figure it out.

**Comment by gmartsenkov** [comment] 2022-06-14 15:53
Is it because i'm calling `require("...")` in the overrides? For example: 
```lua
  override = {
    ["hrsh7th/nvim-cmp"] = {
      sources = {
        { name = "nvim_lsp", max_item_count = 8 },
        { name = "path" },
      },
      mapping = {
        ["<C-j>"] = require("cmp").mapping.select_next_item(),
        ["<C-k>"] = require("cmp").mapping.select_prev_item()
      }
    },
}
```

**Comment by siduck** [comment] 2022-06-14 17:29
@gmartsenkov https://github.com/NvChad/NvChad/commit/0bde81a074f95a6e5096989d0f229bc221ead683#commitcomment-76089641 this guy faces the same issue. I tried his config and cmp was causing this i think

**Comment by siduck** [comment] 2022-06-14 17:58
try my override config https://github.com/siduck/dotfiles/tree/master/nvchad and see

**Comment by siduck** [comment] 2022-06-15 00:42
as your issue seems to be fixed ( shared from discord ) 
![image](https://user-images.githubusercontent.com/59060246/173712487-1ae3948c-ebca-43dc-b208-c84f088e5218.png)


i will be closing this

**Closed by siduck** 2022-06-15 00:42 UTC

**Comment by siduck** [comment] 2022-06-15 00:50
> The problem maybe in `custom/override.lua` file, these plugins are lazy loaded
> 
> ```lua
> local luasnip = require("luasnip")
> local cmp = require("cmp")
> ```

@jrozhon never have this in your override lua, you should know that we lazy load those plugins and the user config is called before those plugins are loaded so ofc it will break everything 

# Things you can do :

1. redefine your cmp config ( read from here , this guy had the same issue as you  ) 

2. Or disable lazy loading for cmp ( you should know how to redefine packer definition of a plugin )

SOOOO : 

```lua
 ["rafamadriz/friendly-snippets"] = {
      after = "base46"
   },
   ```
   
   in your custom plugins section and do packersync
   
   That code will merge with default friendly snippets table and the result will be  
   
   ```lua
  ["rafamadriz/friendly-snippets"] = {
      after = "base46",
      module = "cmp_nvim_lsp",
      event = "InsertEnter",
   },
```

So here packer will favor "after" keyword first  meaning that the module or event fields wont matter
