### ISSUE TITLE
No highlight for JSX tags

### ISSUE THREAD

**Issue by ShinyKiwis** [NvChad/NvChad#1640] opened 2022-10-19 04:38 UTC
I have updated NvChad as well as my nvim to version 0.8.0 and also run the PackerSync
**Describe the bug**
After install the parser for Javascript with TSInstall, the highlight for JSX tags such as div, h2, h3, ... are broken. 
The highlight will work again after reselect the theme.

**To Reproduce**
1. Open any file contain JSX code'
2. Reselect the theme

**Expected behavior**
![image](https://user-images.githubusercontent.com/98898032/196598456-7d3f4010-01f7-4fc1-a514-071149bf8ca9.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/98898032/196598412-6a6f65c7-7661-4ccb-b826-cc47179033bf.png)
![image](https://user-images.githubusercontent.com/98898032/196598350-e00b8ae0-c0a9-444b-b42b-ec8df3c86198.png)

**Desktop: **
- Operating System: Ubuntu
- Window manager: BSPWM
- Terminal: Kitty
- NVIM: 0.8.0

**Additional Context: **
Other parser such as cpp, rust, python work normally

**Comment by kidp2h** [comment] 2022-10-19 09:04
Can you show output command `:checkhealth nvim-treesitter` ?

**Comment by kidp2h** [comment] 2022-10-19 09:09
This problem may be caused by the highlight group name @tag, it isn't defined

**Comment by kidp2h** [comment] 2022-10-19 09:09
you can try with html

**Comment by siduck** [comment] 2022-10-19 12:35
sorry for the delay guys, I missed out that hl group while migrating to new treesitter hl groups in base46's recent commit.

Do a packersync, should be fixed

**Closed by siduck** 2022-10-19 12:35 UTC

**Comment by ShinyKiwis** [comment] 2022-10-19 15:37
I apologize for such late reply, thank you all for your help and information. Everything works perfectly again now :smile:
