### ISSUE TITLE
Telescope error

### ISSUE THREAD

**Issue by insidersbuilt** [NvChad/NvChad#308] opened 2021-08-20 08:23 UTC
when ever i open the nvim it shows me this error and :Telescope does not opens
![image](https://user-images.githubusercontent.com/87114084/130203735-a0b8e389-1ef1-486e-b3d4-8aeab9d69bd3.png)

**Comment by siduck76** [comment] 2021-08-20 08:31
when was the last time you updated nvchad? I released v1.0 yesterday night and the updater has been added + it will work for v1.0  + and master , can you reinstal nvchad again?

**Comment by siduck76** [comment] 2021-08-20 08:31
https://nvchad.netlify.app/docs/getting%20started/setup/

**Comment by ashincoder** [comment] 2021-08-20 08:46
Just reinstall NvChad...

**Comment by pathakraul** [comment] 2021-08-20 09:26
I have installed the latest 1.0 and getting the same issue
![image](https://user-images.githubusercontent.com/23165276/130212241-dd782205-05de-4cbd-befc-fd21a23d35a0.png)

**Comment by siduck76** [comment] 2021-08-20 09:30
> I have installed the latest 1.0 and getting the same issue
> ![image](https://user-images.githubusercontent.com/23165276/130212241-dd782205-05de-4cbd-befc-fd21a23d35a0.png)

can you try the master? https://nvchad.netlify.app/docs/getting%20started/setup/

if it works then I'll update the release

**Comment by pathakraul** [comment] 2021-08-20 09:32
I did exactly this only to install 
```
git clone https://github.com/NvChad/NvChad ~/.config/nvim
nvim +PackerSync
```

**Comment by siduck76** [comment] 2021-08-20 09:33
> I did exactly this only to install
> 
> ```
> git clone https://github.com/NvChad/NvChad ~/.config/nvim
> nvim +PackerSync
> ```

show  nvim -v output

**Comment by pathakraul** [comment] 2021-08-20 09:33
```
NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-FRpcxt/neovim-0.6.0~ubuntu1+git202108191154-7bff64216-adeb5640f=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-FRpcxt/neovim-0.6.0~ubuntu1+git202108191154-7bff64216-adeb5640f/build/config -I/build/neovim-FRpcxt/neovim-0.6.0~ubuntu1+git202108191154-7bff64216-adeb5640f/src -I/build/neovim-FRpcxt/neovim-0.6.0~ubuntu1+git202108191154-7bff64216-adeb5640f/.deps/usr/include -I/usr/include -I/build/neovim-FRpcxt/neovim-0.6.0~ubuntu1+git202108191154-7bff64216-adeb5640f/build/src/nvim/auto -I/build/neovim-FRpcxt/neovim-0.6.0~ubuntu1+git202108191154-7bff64216-adeb5640f/build/include
Compiled by buildd@lgw01-amd64-018

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by siduck76** [comment] 2021-08-20 09:34
> Is it tied to nvim 0.5??
> 
> ```
> NVIM v0.6.0-dev
> Build type: RelWithDebInfo
> LuaJIT 2.1.0-beta3
> Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-FRpcxt/neovim-0.6.0~ubuntu1+git202108191154-7bff64216-adeb5640f=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-FRpcxt/neovim-0.6.0~ubuntu1+git202108191154-7bff64216-adeb5640f/build/config -I/build/neovim-FRpcxt/neovim-0.6.0~ubuntu1+git202108191154-7bff64216-adeb5640f/src -I/build/neovim-FRpcxt/neovim-0.6.0~ubuntu1+git202108191154-7bff64216-adeb5640f/.deps/usr/include -I/usr/include -I/build/neovim-FRpcxt/neovim-0.6.0~ubuntu1+git202108191154-7bff64216-adeb5640f/build/src/nvim/auto -I/build/neovim-FRpcxt/neovim-0.6.0~ubuntu1+git202108191154-7bff64216-adeb5640f/build/include
> Compiled by buildd@lgw01-amd64-018
> 
> Features: +acl +iconv +tui
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/usr/share/nvim"
> 
> Run :checkhealth for more info
> ```

could you use 0.5 stable?

**Comment by Akianonymus** [comment] 2021-08-20 09:36
> I did exactly this only to install
> 
> ```
> git clone https://github.com/NvChad/NvChad ~/.config/nvim
> nvim +PackerSync
> ```

After installation, do this

`nvim -Vlog`

it will create a log file, upload the file and send link here.

**Comment by pathakraul** [comment] 2021-08-20 09:53
Same issue with nvim 0.5 also.
[log.txt](https://github.com/NvChad/NvChad/files/7020684/log.txt)

**Comment by ashincoder** [comment] 2021-08-20 10:48
> I did exactly this only to install
> 
> ```
> git clone https://github.com/NvChad/NvChad ~/.config/nvim
> nvim +PackerSync
> ```

Try to do the following:
```
rm -rf ~/.config/cache/nvim
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim
```

then: 
```
git clone https://github.com/NvChad/NvChad ~/.config/nvim
nvim +PackerSync
```

**Comment by Akianonymus** [comment] 2021-08-20 10:50
@pathakraul I saw the logs, that is surely weird, even the log is totally useless

**Comment by G-Rowell** [comment] 2021-08-20 10:53
I took a look at the logs as well, and agree that they were missing something.

Totally strange here :thinking: 

My next idea would be a missing system package that `Packer` depends on to build maybe?
But that's surely far-fetched?

**Comment by ashincoder** [comment] 2021-08-20 10:56
> when ever i open the nvim it shows me this error and :Telescope does not opens
> ![image](https://user-images.githubusercontent.com/87114084/130203735-a0b8e389-1ef1-486e-b3d4-8aeab9d69bd3.png)

Is this ur config ? :confused: @insidersbuilt

**Comment by ashincoder** [comment] 2021-08-20 10:58
@Akianonymus and @G-Rowell don't u think this is a little sus ?

**Comment by siduck76** [comment] 2021-08-20 10:59
> > when ever i open the nvim it shows me this error and :Telescope does not opens
> > ![image](https://user-images.githubusercontent.com/87114084/130203735-a0b8e389-1ef1-486e-b3d4-8aeab9d69bd3.png)
> 
> Is this ur config ?  @insidersbuilt

update your config to v1.0!

**Comment by pathakraul** [comment] 2021-08-20 11:07
> > I did exactly this only to install
> > ```
> > git clone https://github.com/NvChad/NvChad ~/.config/nvim
> > nvim +PackerSync
> > ```
> 
> Try to do the following:
> 
> ```
> rm -rf ~/.config/cache/nvim
> rm -rf ~/.config/nvim
> rm -rf ~/.local/share/nvim
> ```
> 
> then:
> 
> ```
> git clone https://github.com/NvChad/NvChad ~/.config/nvim
> nvim +PackerSync
> ```

I have already tried this multiple times. Does not change anything.

**Comment by ashincoder** [comment] 2021-08-20 11:08
Are u using ur custom config

**Comment by pathakraul** [comment] 2021-08-20 11:10
Does .vimrc in the home folder affects this?
I don't have any changes in .config/nvim though

**Comment by ashincoder** [comment] 2021-08-20 11:10
I don't mean it this way . What I am asking is are u using custom neovim config .. not vim config.

**Comment by G-Rowell** [comment] 2021-08-20 11:11
Your `.vimrc` shouldn't change it in any way, as there is an `init.lua` file present 

hmmm

**Comment by pathakraul** [comment] 2021-08-20 11:11
Ok, no there are no custom changes any where.

**Comment by ashincoder** [comment] 2021-08-20 11:12
Mhhh .. This seems weird. It used to work with no problem.

**Comment by pathakraul** [comment] 2021-08-20 11:16
Can you tell me the lua version you have tested . I have currently lua 5.3 installed

**Comment by G-Rowell** [comment] 2021-08-20 11:17
> Can you tell me the lua version you have tested . I have currently lua 5.3 installed

Lua is bundled with NeoVim, Lua 5.1

But it's bundled so shouldn't make a difference?

**Comment by siduck76** [comment] 2021-08-20 11:17
> Does .vimrc in the home folder affects this?
> I don't have any changes in .config/nvim though

no , maybe try moving into a different dir and check . Who knows it may work :laughing:

**Comment by G-Rowell** [comment] 2021-08-20 11:18
I'm working on a minimal working config for you @pathakraul 

That probably the best debugging step rn I think

**Comment by ashincoder** [comment] 2021-08-20 11:18
@siduck76 please merge #312. This solves an error regarding statusline.

**Comment by pathakraul** [comment] 2021-08-20 11:19
Sure, thanks.

Will also check by removing vimrc

**Comment by ashincoder** [comment] 2021-08-20 11:19
![2021-08-20-164936_1366x748_scrot](https://user-images.githubusercontent.com/83629316/130225811-34e971da-588e-48f0-804a-4848ec3dd1ca.png)

**Comment by siduck76** [comment] 2021-08-20 11:20
@ashincoder merged already.

**Comment by ashincoder** [comment] 2021-08-20 11:20
This was the error when I installed NvChad. I installed by removing all the .local/nvim .config/nvim

**Comment by ashincoder** [comment] 2021-08-20 11:20
@pathakraul can u test now.

**Comment by pathakraul** [comment] 2021-08-20 11:21
How come I never got this error. Will check

**Comment by ashincoder** [comment] 2021-08-20 11:22
u may not have removed .local/share/nvim.

**Comment by pathakraul** [comment] 2021-08-20 11:24
removed the vimrc and repeated the installation steps also (also removed everything first). Same issue

**Comment by Akianonymus** [comment] 2021-08-20 11:24
Obviously that was not the problem

**Comment by Akianonymus** [comment] 2021-08-20 11:25
> removed the vimrc and repeated the installation steps also (also removed everything first). Same issue

Try disabling packer.

**Comment by pathakraul** [comment] 2021-08-20 11:25
How?

**Comment by ashincoder** [comment] 2021-08-20 11:26
> Obviously that was not the problem

But I have resolved an unknown problem @Akianonymus :laughing: .
Disable packer in chadrc.lua

**Comment by Akianonymus** [comment] 2021-08-20 11:26
> > Obviously that was not the problem
> 
> But I have resolved an unknown problem @Akianonymus 😆 .

Yes, due to my recent config pr.

**Comment by ashincoder** [comment] 2021-08-20 11:28
@pathakraul can u take a screenshot of ur error message

**Comment by pathakraul** [comment] 2021-08-20 11:29
It was attached above 
![image](https://user-images.githubusercontent.com/23165276/130226734-fdac25b3-f60f-48b8-a210-2b2eb3d9a93b.png)

**Comment by ashincoder** [comment] 2021-08-20 11:29
can u take full screenshot I mean

**Comment by pathakraul** [comment] 2021-08-20 11:33
![image](https://user-images.githubusercontent.com/23165276/130227140-b242fac6-6dfa-447a-9cc2-31386573b9c5.png)

**Comment by ashincoder** [comment] 2021-08-20 11:34
OMG :scream: that is a weird error. Can u update ur lua version. I am using lua 5.4.3

**Comment by G-Rowell** [comment] 2021-08-20 11:35
Testing 

![image](https://user-images.githubusercontent.com/3367398/130227335-878b819d-2fa0-4649-bfdd-9c14070b08be.png)

**Comment by ashincoder** [comment] 2021-08-20 11:35
How do this happen @G-Rowell

**Comment by Akianonymus** [comment] 2021-08-20 11:35
> OMG 😱 that is a weird error. Can u update ur lua version. I am using lua 5.4.3

The system lua doesn't matter, in any way

**Comment by pathakraul** [comment] 2021-08-20 11:36
I thought lua is bundled with neovim. My ubuntu 20.04 does not have 5.4 in package list. I will  take a while to try that manually.

**Comment by ashincoder** [comment] 2021-08-20 11:36
@G-Rowell how did u reproduce this.

**Comment by G-Rowell** [comment] 2021-08-20 11:36
Packer is not configured & set up properly, hence the issue I got.

Let me keep working and I'll come back

**Comment by G-Rowell** [comment] 2021-08-20 11:37
> I thought lua is bundled with neovim. My ubuntu 20.04 does not have 5.4 in package list. I will take a while to try that manually.

Don't bother fiddling with your system lua yet my friend! :)

**Comment by pathakraul** [comment] 2021-08-20 11:37
Overall guys, NvChad is awesome.

**Comment by G-Rowell** [comment] 2021-08-20 11:38
> Overall guys, NvChad is awesome.

Hopefully we can get you sorted!
Thanks so much for holding in here with us while we all figure it out :smile:

**Comment by G-Rowell** [comment] 2021-08-20 11:41
More debugging, 

I have a working Packer (including work `:PackerSync`)
but still

![image](https://user-images.githubusercontent.com/3367398/130227949-cedf5772-4d1d-4199-8de1-6c3858d3f78a.png)

**Comment by ashincoder** [comment] 2021-08-20 11:41
Can u show the packer code used

**Comment by G-Rowell** [comment] 2021-08-20 11:43
# init.lua
```
require("plugins")
```
# lua/plugins.lua
```
local present, _ = pcall(require, "packerInit")
local packer

local packer

if present then
        packer = require "packer"
else
   return false
end

local use = packer.use

return packer.startup(function()
   use {
      "wbthomason/packer.nvim",
      event = "VimEnter",
   }

   use {
      "nvim-lua/plenary.nvim",
   }
   use {
      "nvim-telescope/telescope.nvim",
       requires = { {'nvim-lua/plenary.nvim'} }
   }

end)
```

# packerInit.lua
*same as repo std*

**Comment by G-Rowell** [comment] 2021-08-20 11:43
This must be a dependency issue within `plugins.lua`

**Comment by ashincoder** [comment] 2021-08-20 11:45
But my real question is how can @pathakraul reproduce a problem which we can't. It is really susy

**Comment by G-Rowell** [comment] 2021-08-20 11:45
> But my real question is how can @pathakraul reproduce a problem which we can't. It is really susy

I'm sort of reproducing it aren't I?

**Comment by siduck76** [comment] 2021-08-20 11:45
> More debugging,
> 
> I have a working Packer (including work `:PackerSync`)
> but still
> 
> ![image](https://user-images.githubusercontent.com/3367398/130227949-cedf5772-4d1d-4199-8de1-6c3858d3f78a.png)

is this a packer issue?

**Comment by ashincoder** [comment] 2021-08-20 11:46
This is a pretty good first issue

**Comment by G-Rowell** [comment] 2021-08-20 11:46
HAHHAHHAH GOOD FIRST ISSUE
:rofl:

**Comment by ashincoder** [comment] 2021-08-20 11:46
> > But my real question is how can @pathakraul reproduce a problem which we can't. It is really susy
> 
> I'm sort of reproducing it aren't I?
> 
> Well, exact same error msg at least

No my questiion is why isn't this error in NvChad.

**Comment by G-Rowell** [comment] 2021-08-20 11:47
@pathakraul 

https://github.com/NvChad/NvChad/issues/308#issuecomment-902633711

Could you try only having this as your nvim config?
Make sure nothing else at all is there,
so backup with `mv ~/.config/nvim ~/.config/Nvim`

**Comment by G-Rowell** [comment] 2021-08-20 11:47
> > > But my real question is how can @pathakraul reproduce a problem which we can't. It is really susy
> > 
> > 
> > I'm sort of reproducing it aren't I?
> > Well, exact same error msg at least
> 
> No my questiion is why isn't this error in NvChad.

What do you mean?
As in `why are we trying to solve it here?`
Or `why don't other people get this issue?`

I'm not sure I understand

**Comment by ashincoder** [comment] 2021-08-20 11:48
why don't other people get this issue?

> > > > But my real question is how can @pathakraul reproduce a problem which we can't. It is really susy
> > > 
> > > 
> > > I'm sort of reproducing it aren't I?
> > > Well, exact same error msg at least
> > 
> > 
> > No my questiion is why isn't this error in NvChad.
> 
> What do you mean?
> As in `why are we trying to solve it here?`
> Or `why don't other people get this issue?`
> 
> I'm not sure I understand

why don't others get it.

**Comment by G-Rowell** [comment] 2021-08-20 11:49
Ahhhhhhhhh, 
good question

I just got it, but have yet to find what exactly causes it

**Comment by ashincoder** [comment] 2021-08-20 11:49
@pathakraul can u do :checkhealth

**Comment by G-Rowell** [comment] 2021-08-20 11:50
Maybe related?

Telescope issue https://github.com/nvim-telescope/telescope.nvim/issues/1125

**Comment by G-Rowell** [comment] 2021-08-20 11:50
They had some breaking bug apparently today?

**Comment by ashincoder** [comment] 2021-08-20 11:53
But it is solved right

**Comment by pathakraul** [comment] 2021-08-20 11:54
> @pathakraul
> 
> # This should reproduce the problem hopefully can you verify?
> [#308 (comment)](https://github.com/NvChad/NvChad/issues/308#issuecomment-902633711)
> 
> Could you try only having this as your nvim config?
> Make sure nothing else at all is there,
> so backup with `mv ~/.config/nvim ~/.config/Nvim`

I tried two things - 
1. Only init.lua with `require("plugins")`
Output - 
```
Error detected while processing /home/rpathak/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/rpathak/.config/nvim/init.lua:1: module 'plugins' not found:
        no field package.preload['plugins']
        no file './plugins.lua'
        no file '/usr/share/luajit-2.1.0-beta3/plugins.lua'
        no file '/usr/local/share/lua/5.1/plugins.lua'
        no file '/usr/local/share/lua/5.1/plugins/init.lua'
        no file '/usr/share/lua/5.1/plugins.lua'
        no file '/usr/share/lua/5.1/plugins/init.lua'
        no file './plugins.so'
        no file '/usr/local/lib/lua/5.1/plugins.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/plugins.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```

2. Created lua/plugins.lua with content as per the https://github.com/NvChad/NvChad/issues/308#issuecomment-902633711
Output -
No error

**Comment by G-Rowell** [comment] 2021-08-20 11:57
No sorry XD

I need you to `mv ~/.config/nvim ~/.config/Nvim`

This will `backup & wipe your NeoVim config`

Then `mkdir -p ~/.config/nvim/lua`

Then `touch ~/.config/nvim/init.lua`
`touch ~/.config/nvim/lua/packerInit.lua`
`touch ~/.config/nvim/lua/plugins.lua`

The copy all of the files from my comment here https://github.com/NvChad/NvChad/issues/308#issuecomment-902633711

**Comment by G-Rowell** [comment] 2021-08-20 11:58
We want your config to be only these files I'm giving you,

you have linked what I would like as `init.lua` & `plugins.lua`

And set `packerInit.lua` as this https://raw.githubusercontent.com/NvChad/NvChad/main/lua/packerInit.lua

**Comment by G-Rowell** [comment] 2021-08-20 11:59
The enter & restart NeoVim

Enter & hopefully `:PackerSync` is a command,
run it

restart neovim

Run `:Telecope`

## this should make the error appear, that's good because it means it's predicitable

**Comment by G-Rowell** [comment] 2021-08-20 12:00
Then I will continue debugging & try decipher what it is,

I know this isn't a solution yet.
But a minimal working example that generates the error is vital to debugging

**Comment by G-Rowell** [comment] 2021-08-20 12:01
Again @pathakraul,

really appreciate your help & patience with this, we'll get to the bottom of this!

If I'm being confusing, I'm also happy to `.zip` my files to send to you for easier testing

Thanks again, so sorry for all this hassle!

**Comment by pathakraul** [comment] 2021-08-20 12:05
Not an issue.

- These are the initial files and the content is same which you asked.
```
nvim
├── init.lua
└── lua
    ├── packerInit.lua
    └── plugins.lua

```
- Restart nvim and PackerSync shows that everything is up to date
- Restart nvim again and Telescope shows same error

**Comment by G-Rowell** [comment] 2021-08-20 12:06
Okay, great!

We're both having the exact same (original) and repeatable issue

**Comment by G-Rowell** [comment] 2021-08-20 12:07
I gtg for a bit, it's quite late in Australia rn and have to attend to a few things urgently

I will debug this later some more later tonight and will be back as soon as I can!

**Comment by G-Rowell** [comment] 2021-08-20 12:07
Don't worry about doing much more yourself until I get back to you

**Comment by pathakraul** [comment] 2021-08-20 12:08
Enjoy @G-Rowell . thanks

**Comment by insidersbuilt** [comment] 2021-08-20 12:28
> > when ever i open the nvim it shows me this error and :Telescope does not opens
> > ![image](https://user-images.githubusercontent.com/87114084/130203735-a0b8e389-1ef1-486e-b3d4-8aeab9d69bd3.png)
> 
> Is this ur config ?  @insidersbuilt

yes

**Comment by G-Rowell** [comment] 2021-08-20 14:04
@pathakraul 

Looks like it's upstream?

**Comment by insidersbuilt** [comment] 2021-08-20 15:44
The bug is in the telescope plugin because i didn't update the nvchad from about 4  days

**Comment by ashincoder** [comment] 2021-08-20 15:56
I think it is safe to close this error since it is a telescope error.

**Comment by siduck76** [comment] 2021-08-20 16:34
> I think it is safe to close this issue since it is a telescope error.

lets wait for a day or two.

**Comment by insidersbuilt** [comment] 2021-08-20 21:05
> Are u using ur custom config

yes

**Comment by siduck76** [comment] 2021-08-21 10:36
@insidersbuilt can you update your  nvchad config and check it again?

**Comment by siduck76** [comment] 2021-08-21 11:58
> I think it is safe to close this issue since it is a telescope error.

Agreed.

**Closed by siduck76** 2021-08-21 11:58 UTC
Labels: good first issue
