### ISSUE TITLE
Copy and paste  line end 

### ISSUE THREAD

**Issue by tomasky** [NvChad/NvChad#1109] opened 2022-05-21 02:54 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 -  linux 
 - Terminal
 - 0.7.0
 
the latest nvchad and latest plugins,  default nvchad config

**Additional context**

file `some.md`
```md
key->abc
key->mkn
```

copy `abc`
paste and override `mkn`, then the result :
```md
key->abc
key-abc>
```

**Comment by siduck** [comment] 2022-05-21 03:40
whats the expected behaviour? im confused

**Comment by zbirenbaum** [comment] 2022-05-21 03:42
Are you saying that after yanking abc and visually selecting mkn and pasting abc over it, that is the result?

**Comment by tomasky** [comment] 2022-05-21 03:46
> Are you saying that after yanking abc and visually selecting mkn and pasting abc over it, that is the result?

Yes

**Comment by zbirenbaum** [comment] 2022-05-21 03:58
> > Are you saying that after yanking abc and visually selecting mkn and pasting abc over it, that is the result?
> 
> 
> 
> Yes 

@siduck reproduced this. Didn't happen with my custom config but did with vanilla. Think that means it's a plugin problem 

I also just found out though that my NvChad config doesn't work with vanilla NvChad anymore as of a recent patch so I can't offer much more info than that at the moment...

**Comment by siduck** [comment] 2022-05-21 04:03
@zbirenbaum you should avoid making changes out of the custom dir, as you're a core member of the org, It'll be better for you to use vanilla nvchad + custom config as I think it would not be appropriate for a core nvchad dev to not use the original nvchad ._.

**Comment by zbirenbaum** [comment] 2022-05-21 04:05
> @zbirenbaum you should avoid making changes out of the custom dir, as you're a core member of the org, It'll be better for you to use vanilla nvchad + custom config as I think it would not be appropriate for a core nvchad dev to not use the original nvchad 

@siduck while I agree, the recent color plugin changes messed up a lot of stuff I haven't had a chance to rewrite, so it was unfortunately necessary. Even though I remove all default plugins I still error out somehow.

**Comment by siduck** [comment] 2022-05-21 04:13
@zbirenbaum the base46 plugin is complete ig, its compatible with 0.7 and it has been simplified. Im not sure why would the base46 plugin trouble you, also why remove all the plugins? you dont use them, just try to control the defaults within the custom config, read the docs as there have been major changes recently and if you err somehow then let me know, i'll help you

**Comment by zbirenbaum** [comment] 2022-05-21 04:14
@siduck turns out I was just on an old PR branch and forgot. I did find the issue though. Why on earth is there now an nvchad global instead of core.utils?

**Comment by zbirenbaum** [comment] 2022-05-21 04:37
@siduck I'm getting some index string upvalue error even after fixing all the other stuff I wasn't getting on older branches. Any idea what that might be from? There's no line numbers or any info whatsoever to guide me.

**Comment by zbirenbaum** [comment] 2022-05-21 05:14
Anyways, back on topic, this line in misc_mappings found in plugins.config.others is to blame for the issue:

`map("v", "p", '"_dP')`

The previous mapping committed by aki 
`map("v", "p", 'p:let @+=@0<CR>:let @"=@0<CR>', { silent = true })` doesn't cause the problem. I'm not sure if that was changed for a reason though, so I'll leave reverting it up to you @siduck

**Comment by tomasky** [comment] 2022-05-21 05:33
But if line start：
```md
abc->key
mkn->key
```
the result :
```md
abc->key
-abc>key
```

**Comment by zbirenbaum** [comment] 2022-05-21 05:38
> But if line start：
> 
> ```md
> 
> abc->key
> 
> mkn->key
> 
> ```
> 
> the result :
> 
> ```md
> 
> abc->key
> 
> -abc>key
> 
> ```
> 
> 
> 
> 

Commit amended, try now.

**Comment by zbirenbaum** [comment] 2022-05-21 05:46
Reopening because the code doesn't "not copy the selected text" as claimed. Neither of the versions given by aki seem to correctly. 

Personally this is a "feature" I wouldn't want hard coded into the mappings and forced on everyone anyways.

I think it's best to leave paste (as a core neovim behavior) functionality up to the users and remove this entirely for now @siduck

**Comment by siduck** [comment] 2022-05-21 06:49
> Reopening because the code doesn't "not copy the selected text" as claimed. Neither of the versions given by aki seem to do this correctly, but both of the "_d ones have problems too.
> 
> I've removed the offending line entirely for now, as each command supplied causes a different issue. Personally this is a "feature" I wouldn't want hard coded into the mappings and forced on everyone anyways, as I think it's best to just leave paste (as a core neovim behavior) functionality up to the users
> 
> If removing that line and allowing users to set it on their own is acceptable to you, you can probably go ahead and close this issue @siduck
> 
> On another note, I find the wrapped line movement disagreeable for the same reason to a slightly lesser degree. I think it should be considered if that could just be a snippet supplied in the docs and then removed from core.

I agree with it, you may remove it :v

**Closed** 2022-05-21 06:50 UTC
