### ISSUE TITLE
which-key directly access the secondary menu 

### ISSUE THREAD

**Issue by xarthurx** [NvChad/NvChad#1067] opened 2022-05-12 20:39 UTC
**Describe the bug**
Glat that the `which-key` plugin is added.
After testing, there is one issue kind of buggy:

I notice that the menu will only show up after pressing `<leader> and waiting for some ms.
However, this only works for `<leader>`.

For instance, I press `<leader>` the menu shows, and I can press the next key based on the menu.
If I know I want to use`telescope`, but not sure which function, I want to press `<leader>f` and choose the secondary menu -- but in this case, the menu doesn't show up.

I'm not sure if this is actually achievable...

**Comment by LeonHeidelbach** [comment] 2022-05-12 23:07
@xarthurx that's because there is also a function mapped to `<leader>f`, which would be "floating diagnostics". Pressing `<leader>f` too quickly will in this case just trigger the command. You have to first press `<leader>` wait until the popup shows up and then press `f` to see the telescope options. This is expected behaviour. This issue can be closed.

**Comment by siduck** [comment] 2022-05-13 05:56
@LeonHeidelbach how do we show up all mappings associated with leader?
 
 :whichkey <leader> didnt work , it just shows this 
 
 
![image](https://user-images.githubusercontent.com/59060246/168220223-b0b40285-9970-4ff2-854e-a921cdb5f370.png)


i cant even scroll!

**Comment by siduck** [comment] 2022-05-13 05:57
i was expectiving a big popup like this :whichkey cmd
![image](https://user-images.githubusercontent.com/59060246/168220279-97255172-2ef3-4234-a69d-28a048f9aae4.png)

**Comment by LeonHeidelbach** [comment] 2022-05-13 06:04
>  @LeonHeidelbach how do we show up all mappings associated with leader?
> 
>  
> 
>  :whichkey <leader> didnt work , it just shows this 
> 
>  
> 
>  
> 
> ![image](https://user-images.githubusercontent.com/59060246/168220223-b0b40285-9970-4ff2-854e-a921cdb5f370.png)
> 
> 
> 
> 
> 
> i cant even scroll!

@siduck Well that's probably because there are no more mappings directly associated with `<leader>`. The others are in lower levels. But you can merge my PR and use `<leader>wK` to show all mappings or `<leader>wk` to get a query prompt where you can type in for which key you would like to see all options.

**Comment by siduck** [comment] 2022-05-13 06:05
> > @LeonHeidelbach how do we show up all mappings associated with leader?
> > :whichkey  didnt work , it just shows this
> > ![image](https://user-images.githubusercontent.com/59060246/168220223-b0b40285-9970-4ff2-854e-a921cdb5f370.png)
> > i cant even scroll!
> 
> @siduck Well that's probably because there are no more mappings directly associated with `<leader>`. The others are in lower levels. But you can merge my PR and use `<leader>wK` to show all mappings or `<leader>wk` to get a query prompt where you can type in for which key you would like to see all options.

alerady merged

**Comment by siduck** [comment] 2022-05-13 06:08
@LeonHeidelbach :WhichKey still doesnt show all mappings tho!  Idk if there's a way to show all nvchad mappings at one place :think

**Comment by LeonHeidelbach** [comment] 2022-05-13 06:12
> @LeonHeidelbach :WhichKey still doesnt show all mappings tho!  Idk if there's a way to show all nvchad mappings at one place :thinking: 

@siduck which mappings are not showing for you? I see everything that is mapped for the respective mode and prefix key. If you use `<leader>wk` you can type for example `Whichkey: <leader> v` into the prompt and you will get all mappings for `<leader>` in visual mode.

**Comment by siduck** [comment] 2022-05-13 06:13
> > @LeonHeidelbach :WhichKey still doesnt show all mappings tho!  Idk if there's a way to show all nvchad mappings at one place thinking
> 
> @siduck which mappings are not showing for you? I see everything that is mapped for the respective mode and prefix key. If you use `<leader>wk` you can type for example `Whichkey: <leader> v` into the prompt and you will get all mappings for `<leader>` in visual mode.

leader fa, ff etc

**Comment by LeonHeidelbach** [comment] 2022-05-13 06:16
> > > @LeonHeidelbach :WhichKey still doesnt show all mappings tho!  Idk if there's a way to show all nvchad mappings at one place thinking
> 
> > 
> 
> > @siduck which mappings are not showing for you? I see everything that is mapped for the respective mode and prefix key. If you use `<leader>wk` you can type for example `Whichkey: <leader> v` into the prompt and you will get all mappings for `<leader>` in visual mode.
> 
> 
> 
> leader fa, ff etc

@siduck you will see those after typing `<leader>` waiting for the popup to show, and then pressing `f`. 

I don't think you can just print all custom mappings regardless of which mode or level they are in. You can only ever see all mappings for one key in the current level. So all options for `f` will be shown after pressing `f`.

**Comment by siduck** [comment] 2022-05-13 06:31
> > > > @LeonHeidelbach :WhichKey still doesnt show all mappings tho!  Idk if there's a way to show all nvchad mappings at one place thinking
> > 
> > 
> > > 
> > 
> > 
> > > @siduck which mappings are not showing for you? I see everything that is mapped for the respective mode and prefix key. If you use `<leader>wk` you can type for example `Whichkey: <leader> v` into the prompt and you will get all mappings for `<leader>` in visual mode.
> > 
> > 
> > leader fa, ff etc
> 
> @siduck you will see those after typing `<leader>` waiting for the popup to show, and then pressing `f`.
> 
> I don't think you can just print all custom mappings regardless of which mode or level they are in. You can only ever see all mappings for one key in the current level. So all options for `f` will be shown after pressing `f`.

yep ik, just realized we have :Telescope keymaps for it xD

**Comment by LeonHeidelbach** [comment] 2022-05-13 06:39
> > > > > @LeonHeidelbach :WhichKey still doesnt show all mappings tho!  Idk if there's a way to show all nvchad mappings at one place thinking
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > @siduck which mappings are not showing for you? I see everything that is mapped for the respective mode and prefix key. If you use `<leader>wk` you can type for example `Whichkey: <leader> v` into the prompt and you will get all mappings for `<leader>` in visual mode.
> 
> > > 
> 
> > > 
> 
> > > leader fa, ff etc
> 
> > 
> 
> > @siduck you will see those after typing `<leader>` waiting for the popup to show, and then pressing `f`.
> 
> > 
> 
> > I don't think you can just print all custom mappings regardless of which mode or level they are in. You can only ever see all mappings for one key in the current level. So all options for `f` will be shown after pressing `f`.
> 
> 
> 
> yep ik, just realized we have :Telescope keymaps for it xD

@siduck yep, telescope keymaps will definitely be better for that. Somehow they changed the command for that from "keys" to "keymaps" so I changed that in my PR.

**Comment by siduck** [comment] 2022-05-13 11:10
> @xarthurx that's because there is also a function mapped to `<leader>f`, which would be "floating diagnostics". Pressing `<leader>f` too quickly will in this case just trigger the command. If there would be no direct mapping to this key combination, you would be able to immediately get to the secondary level. You have to first press `<leader>` wait until the popup shows up and then press `f` to see the telescope options. This is expected behaviour. This issue can be closed.

so this doesnt seem like an actual issue, closing this

**Closed by siduck** 2022-05-13 11:10 UTC
