### ISSUE TITLE
Theme color not fully applied.

### ISSUE THREAD

**Issue by MrHeer** [NvChad/NvChad#1102] opened 2022-05-19 02:39 UTC
**Describe the bug**
Theme color not fully applied.

**To Reproduce**
1. config `chadrc.lua`
```
M.ui = {
  theme = "one_light",
}
```
2. open `chadrc.lua`
3. <leader>tt

**Expected behavior**
Applied the theme init.

**Screenshots**
![2022-05-19 10 38 24](https://user-images.githubusercontent.com/18595761/169192547-9e78a1f8-fe5b-4e88-97ff-df6ca7ad6005.gif)

**Desktop (please complete the following information):**
 - Operating System: macOS 12.3.1 (21E258)
 - Terminal: iTerm2 3.4.15
 - Version of Neovim: v0.7.0

**Comment by siduck** [comment] 2022-05-19 02:41
duplicate of https://github.com/NvChad/NvChad/issues/1046

**Closed by siduck** 2022-05-19 02:41 UTC

**Comment by MrHeer** [comment] 2022-05-19 02:50
very sorry, I didn't see that.
