### ISSUE TITLE
Themes look weird when terminal has lighter BG set

### ISSUE THREAD

**Issue by nzlov** [NvChad/NvChad#1046] opened 2022-05-09 06:45 UTC
**Describe the bug**
Theme no work when open nvim.

**To Reproduce**
Open nvim.

**Expected behavior**
Theme work.

**Screenshots**
![image](https://user-images.githubusercontent.com/2859981/167354080-277e71e0-3155-4f0f-ad59-626fc4970781.png)

**Desktop (please complete the following information):**
 - Operating System `macos 12.1`
 - Terminal `iTream2`
 - Version of Neovim `NVIM v0.7.0`

**Additional context**
If you switch the theme after opening it, everything becomes normal again.
![image](https://user-images.githubusercontent.com/2859981/167354800-bf3849dc-a32d-4df6-9677-b8cffece4fef.png)

**Comment by siduck** [comment] 2022-05-09 06:59
which theme? i removed some themes recently so its not opening

**Comment by nzlov** [comment] 2022-05-09 07:03
`one_light`
`gruvchad`
`nord`
...

I think all themes.....

**Comment by siduck** [comment] 2022-05-09 07:04
they will work, when was the last time u did nvchad update and packersync?

**Comment by nzlov** [comment] 2022-05-09 07:07
Just now...

**Comment by siduck** [comment] 2022-05-09 07:09
i cant reproduce this issue, you sure you are using 0.7 version of nvim?

**Comment by nzlov** [comment] 2022-05-09 07:10
![image](https://user-images.githubusercontent.com/2859981/167358244-b3ca9df1-43b2-47fc-abf8-55c0153ead15.png)

**Comment by siduck** [comment] 2022-05-09 07:14
https://user-images.githubusercontent.com/59060246/167358812-2764fa4d-4ab9-475a-80f1-0211d6624b52.mp4

**Comment by nzlov** [comment] 2022-05-09 07:14
Oh ..........
Try macos terminal. It's work...

**Comment by siduck** [comment] 2022-05-09 07:15
i cant, I use linux. Try alacritty or wezterm or kitty!!!

**Comment by nzlov** [comment] 2022-05-09 07:16
ok, thx.

**Comment by nzlov** [comment] 2022-05-09 07:21
@siduck Try terminal light theme.

**Comment by nzlov** [comment] 2022-05-09 07:28
https://user-images.githubusercontent.com/2859981/167360737-c3c05a22-1608-4936-9eed-bff114709bef.mov

**Comment by siduck** [comment] 2022-05-09 07:30
@nzlov i can confirm this,  I have the same issue with light theme in alacritty

**Comment by siduck** [comment] 2022-05-10 08:12
@nzlov do u face this issue without nvchad?

**Comment by nzlov** [comment] 2022-05-11 01:18
Last updated Apr 22, 2022, no problem.

**Comment by siduck** [comment] 2022-05-13 12:03
@nzlov tried on st terminal and i dont face this issue

![image](https://user-images.githubusercontent.com/59060246/168279222-5d3ff365-2192-4102-9662-24adc2b3cc6d.png)

alacritty & iterm2 have it. Do u face the issue with wezterm or kitty?

**Comment by nzlov** [comment] 2022-05-14 12:29
Iterm2 with light theme has this problem, macos terminal without this problem.

**Comment by younes-ghorbany** [comment] 2022-05-16 12:42
hi
i have macbook pro m1
every time i remove a plugin and run :PackerSync to confirm the delete and when i reopen nvim always runs into this error and there is no theme and i can't change it
`packer.nvim: Error running config for base46: ...al/share/nvim/site/pack/packer/opt/base46/lua/base46.lua:7: attempt to concatenate local 'name' (a nil value)
packer.nvim: Error running config for feline.nvim: ...al/share/nvim/site/pack/packer/opt/base46/lua/base46.lua:7: attempt to concatenate local 'name' (a nil value)`
if i go to the ~/.local/share/nvim/site/pack/packer/opt/base46/lua/base46.lua i can open theme changer and select the theme but just works here.
in other paths i need to :set autochdir then i can select the theme but if i do this i can't open any terminal.
if i delete everything and clone nvchad again it works without any problem but when i delete a plugin  i get the same error.
sorry for my bad english 😅

**Comment by siduck** [comment] 2022-05-16 12:48
> hi i have macbook pro m1 every time i remove a plugin and run :PackerSync to confirm the delete and when i reopen nvim always runs into this error and there is no theme and i can't change it `packer.nvim: Error running config for base46: ...al/share/nvim/site/pack/packer/opt/base46/lua/base46.lua:7: attempt to concatenate local 'name' (a nil value) packer.nvim: Error running config for feline.nvim: ...al/share/nvim/site/pack/packer/opt/base46/lua/base46.lua:7: attempt to concatenate local 'name' (a nil value)` if i go to the ~/.local/share/nvim/site/pack/packer/opt/base46/lua/base46.lua i can open theme changer and select the theme but just works here. in other paths i need to :set autochdir then i can select the theme but if i do this i can't open any terminal. if i delete everything and clone nvchad again it works without any problem but when i delete a plugin i get the same error. sorry for my bad english sweat_smile

do leader uu and packersync

**Comment by younes-ghorbany** [comment] 2022-05-16 13:04
Thank you 🌹 problem solved 👍

**Comment by siduck** [comment] 2022-05-20 01:56
https://user-images.githubusercontent.com/59060246/169433080-1c564345-12a4-4120-b17c-e638c1865777.mp4


@nzlov this is a very weird issue, I think light background color of terminals like alacritty and iterm2 cause this, can you try the same with iterm2?

**Comment by nzlov** [comment] 2022-05-20 06:01
Iterm2 with light background has this issue, macos terminal without.

**Comment by siduck** [comment] 2022-05-20 06:33
> Iterm2 with light background has this issue, macos terminal without.

ya so this seems that only iterm and alacritty have this issue, But the issue gets solved when we do theme reloading, more weird :thinking:

**Comment by zbirenbaum** [comment] 2022-05-20 08:15
This is more than likely a result of neovim inheriting certain things from the terminal theme. The new highlight api functions differently than the old one, in that an omitted field in setting a highlight group's properties unsets a value. 
e.g.
If current highlight of HL_GROUP_XYZ is `{fg = '#000000'}`

setting HL_GROUP_XYZ to `{bg = '#999999}`

will result in: '{bg = '#999999', fg = 'NONE'}` as the final highlight value

Since I assume the theme switcher uses this api, its possible that it unsets some value that is initially inherited from the terminal, which could vary based on your term info.

If you want to debug this, redirect `:highlight` to some register, paste the register contents into some file, then change the theme and then change it back to the previous one (which should result in same theme without the bug) and do the highlight redirection and paste again. Then, run a diff on the files (you may have to sort them) and you should have your answer as to what is getting changed.

I realize that those instructions might not be super clear anyone unfamiliar with some of normal vim's more advanced features, so alternatively you can wait a couple days and I'll take a stab at it. I'm on linux too, but if this happens in alacritty hopefully I can reproduce it.

**Comment by siduck** [comment] 2022-05-20 08:17
@zbirenbaum the issue gets fixed when I reload the theme tho, very weird

**Comment by zbirenbaum** [comment] 2022-05-20 08:17
> @zbirenbaum the issue gets fixed when I reload the theme tho, very weird

I addressed this specifically above

**Comment by zbirenbaum** [comment] 2022-05-20 08:28
@siduck I gotta head to sleep for now, but here's how to redir stuff in case you want to debug this:

First open a file called theme_broken.txt and run this command:
`:redir @a | highlight | redir END`
then type `G` which will go to the bottom, and then `<CR>` to exit the command output
next, inside normal mode within the text file buffer type the following chars: `"ap`
the `"` means register, `a` is register a, and `p` pastes the contents.

Save the file, and repeat the steps for the theme after it has been reloaded.

if you run diff <file1> <file2> and every line is different, you need to sort the lines which you can do in innumerable ways of your choice, just make sure that they order of them is identical. When you run the diff after sorting, it should only have a couple differences which is where the problem will lie.

**Comment by rauchg** [comment] 2022-05-22 00:04
Running into this as well with Hyper. As @siduck mentioned, if I do `<leader>th` and re-select the theme, triggering a reload, the issue goes away 😬

**Comment by siduck** [comment] 2022-05-22 00:06
> @siduck I gotta head to sleep for now, but here's how to redir stuff in case you want to debug this:
> 
> First open a file called theme_broken.txt and run this command: `:redir @a | highlight | redir END` then type `G` which will go to the bottom, and then `<CR>` to exit the command output next, inside normal mode within the text file buffer type the following chars: `"ap` the `"` means register, `a` is register a, and `p` pastes the contents.
> 
> Save the file, and repeat the steps for the theme after it has been reloaded.
> 
> if you run diff and every line is different, you need to sort the lines which you can do in innumerable ways of your choice, just make sure that they order of them is identical. When you run the diff after sorting, it should only have a couple differences which is where the problem will lie.
> 
> I hate vimscript, but in this scenario there aren't many alternatives. Sorry :(

i see a blank file, can you look onto this issue? :thinking:

**Comment by siduck** [comment] 2022-05-22 00:16
> Running into this as well with Hyper. As @siduck mentioned, if I do `<leader>th` and re-select the theme, triggering a reload, the issue goes away grimacing

I wanted to test it with hyper but hyper doesnt work with mksh here unfortunately :fearful: 
https://user-images.githubusercontent.com/59060246/169673044-441aa2d6-c5d4-42c4-bafd-2c069a72dbbf.mp4

**Comment by siduck** [comment] 2022-05-22 00:34
@rauchg @nzlov  open tmux and run nvim in it, do you see if the theme breaks?

**Comment by rauchg** [comment] 2022-05-22 00:45
Works like a charm in tmux!

**Comment by siduck** [comment] 2022-05-22 00:55
@rauchg whats does this show
```
echo $TERM
```

**Comment by siduck** [comment] 2022-05-22 01:20
## Summarize the issue 

- Light color Bgs on iterm2, alacritty, hyper break nvchad themes where as other terminals work fine with it
- But they get fixed when we reload theme with the theme switcher 
- This issue also gets fixed when we run nvim in tmux

Im out of clue if the issue's from our side or its terminal specific :thinking:

**Comment by siduck** [comment] 2022-05-22 01:20
@LeonHeidelbach

**Comment by rauchg** [comment] 2022-05-22 01:26
`xterm-256color` for Hyper, `screen` inside tmux. I can confirm light colors are also broken in Terminal.app for me, until I go into tmux.

**Comment by siduck** [comment] 2022-05-22 01:28
Very weird that it sets the colorscheme for 1-2 secs then the colorscheme breaks and it gets fixed when I run our colorscheme loading function, check the video 


https://user-images.githubusercontent.com/59060246/169674400-de80df1d-e1ad-46ae-af99-eada29fdae37.mp4

**Comment by zbirenbaum** [comment] 2022-05-22 03:07
@siduck test it with my fork of the old base-16 plugin. Should be able to tell if its related to the colorscheme plugin or not. zbirenbaum/nvim-base16.lua

**Comment by siduck** [comment] 2022-05-22 03:58
@zbirenbaum cant, a lot will be missing in the bufferline,feline devicons highlights, also we no longer have the colors dir too

**Comment by siduck** [comment] 2022-05-22 04:00
```
colors:
  primary:
    background: '0xffffff'
    foreground: '0x000000'
```

~/.config/alacritty/alacritty.yml

**Comment by siduck** [comment] 2022-05-22 04:08
@zbirenbaum we had the same issue before base46, check https://github.com/NvChad/NvChad/issues/516 . I closed it since that was related to alacritty but didnt know it was the issue with many terminals, I tested kitty, gnome terminal too and they have the same issue, only st doesnt break XD

**Comment by siduck** [comment] 2022-05-22 08:55
fixed now, @zbirenbaum we just had to set the bg option, check :h bg

**Closed by siduck** 2022-05-22 08:55 UTC
Labels: bug, help wanted

**Comment by zbirenbaum** [comment] 2022-05-22 15:08
> fixed now, @zbirenbaum we just had to set the bg option, check :h bg
> 
> 

Good to know! I use my term color as my bg so wasn't aware of this, thanks for figuring it out

**Comment by rauchg** [comment] 2022-05-22 23:43
Works like a charm. `<leader>uu` is so nice. God bless NvChad 🥲

**Comment by siduck** [comment] 2022-05-23 00:00
> Works like a charm. `<leader>uu` is so nice. God bless NvChad smiling_face_with_tear

consider starring NvChad if you can :p

**Comment by rauchg** [comment] 2022-05-24 00:45
> > Works like a charm. `<leader>uu` is so nice. God bless NvChad smiling_face_with_tear
> 
> 
> 
> consider starring NvChad if you dont mind, would help us a lot :o 

I did and I also made a PayPal donation. Thanks again to you and the other contributors for the great work!

**Comment by siduck** [comment] 2022-05-24 00:46
oh that was you! thanks a lot :D

**Comment by antony-frolov** [comment] 2023-05-08 08:46
Hi! Did this one get fixed? Seems like I've got the same issue. Dark theme works perfectrly fine tho
<img width="1141" alt="Screenshot 2023-05-08 at 11 45 40" src="https://user-images.githubusercontent.com/69483357/236779153-e8f67a02-d506-46dc-87ef-864f270ae37d.png">

**Comment by siduck** [comment] 2023-05-08 08:57
> Hi! Did this one get fixed? Seems like I've got the same issue. Dark theme works perfectrly fine tho <img alt="Screenshot 2023-05-08 at 11 45 40" width="1141" src="https://user-images.githubusercontent.com/69483357/236779153-e8f67a02-d506-46dc-87ef-864f270ae37d.png">

https://github.com/NvChad/base46/issues/184
