### ISSUE TITLE
Custom leader is not picked/mapped correctly

### ISSUE THREAD

**Issue by cotko** [NvChad/NvChad#1475] opened 2022-08-13 14:54 UTC
**Describe the bug**
Setting custom mapleader in `custom/init.lua` is not set up properly.

When I set a custom leader to `,` which is what I want to use, I get some of my mappings correctly mapped to use my leader, while some mappings stay mapped to default `space` leader.

This started happening with commits that followed 01b17d2ad6d47008b27f38bff7fa490f56fae03f (if I revert to this one things work as expected regarding the leader). 

I've enabled which key (which does not affect this bug, same can be observed through Telescope keymaps if whichkey is disabled) and here are hints that I get when I press my custom mapleader `,`:

![image](https://user-images.githubusercontent.com/795665/184499122-d744a732-f004-40fe-8041-76cef35c7e55.png)

And here is a list when I press `space`:
![image](https://user-images.githubusercontent.com/795665/184499145-2b0a98a0-1396-4685-9928-83f91cdad47d.png)

After messing around a bit with nvchad lua files, Ive found out that if I move the `pcall(require, "custom")` from the bottom to after `core.options` are required, my leader is picked up correctly:
```lua
-- init.lua
...
require "core"
require "core.options"
pcall(require, "custom")

require("core.utils").load_mappings()
...

```

With this change, the which key gives this after I press my custom leader:
![image](https://user-images.githubusercontent.com/795665/184499264-f46fe69c-3a7b-4e88-b766-f9f66ec54537.png)

And pressing space only gives the actual mappings I've mapped to `Space`, without any mappings mapped to `leader`:
![image](https://user-images.githubusercontent.com/795665/184499432-1d59448e-c28f-4c48-85b9-0952c3a2acad.png)

My solution is probably not correct, but it seems there's someting wrong with the order of loading of custom settings.

Btw my custom settings [can be found here](https://github.com/cotko/nvimchad).

**Comment by cj** [comment] 2022-08-13 21:59
@cotko I have the same issue, a quick work around for now is to change it directly here https://github.com/NvChad/NvChad/blob/main/lua/core/options.lua#L58

**Comment by GrizzlT** [comment] 2022-08-13 22:05
I have this issue as well, that fix works for now.

**Comment by cotko** [comment] 2022-08-13 22:06
@cj yes I know, another option is [moving this `pcall(require, "custom")`](https://github.com/NvChad/NvChad/blob/5f23aaf1ca32c41b2bdbca33540e713ff185d5c0/init.lua) from line 25 to line 6 (right after `require "core.options"` :)

**Comment by Akianonymus** [comment] 2022-08-14 13:50
I cannot reproduce this issue, but try this. Move this code in init.lua

```lua
vim.defer_fn(function()
  pcall(require, "impatient")
end, 0)
```

to the bottom of `init.lua`

**Comment by cj** [comment] 2022-08-14 14:01
@Akianonymus that did not work for me. However, @cotko suggestion did.

**Comment by siduck** [comment] 2022-08-15 00:27
> @cj yes I know, another option is [moving this `pcall(require, "custom")`](https://github.com/NvChad/NvChad/blob/5f23aaf1ca32c41b2bdbca33540e713ff185d5c0/init.lua) from line 25 to line 6 (right after `require "core.options"` :)
> 
> (edit: using this ^ for most of today I did not encounter any visible problems yet)

or moving this

```
require("core.utils").load_mappings()
```

to the end of the init.lua fixes it too?

**Comment by siduck** [comment] 2022-08-15 00:27
changed mapleader does work except for some mappings like that from the `general table`

**Closed** 2022-08-15 13:54 UTC
