### ISSUE TITLE
Magnifying glass icon missing on Dashboard

### ISSUE THREAD

**Issue by besnija** [NvChad/NvChad#949] opened 2022-04-11 21:01 UTC
**Describe the bug**
The magnifying icon on the `alpha` dashboard is a `<?>` in `iTerm2`.

**To Reproduce**

1. Open nVIM
2. See error

**Expected behavior**
The icon should be displayed.

**Desktop (please complete the following information):**
 - Operating System - MacOS
 - Terminal - iTerm2
 - Version of Neovim - 0.61

**Screenshot**
![Screen Shot 2022-04-11 at 22 58 08](https://user-images.githubusercontent.com/53597440/162831084-3f91dc74-603e-4833-9aee-9ec48f00bda6.png)

**Additional context**

I was met with such a problem before on `Telescope` but was able to change the icon (issue https://github.com/NvChad/NvChad/issues/939). However I would like to do the same but with `Alpha` this time, but I run into troubles as this time it's a **button** that needs changing.
I scoured through the issues and found the syntax [here](https://github.com/NvChad/NvChad/issues/894#issuecomment-
1076079364) but sadly it didn't function.
Initially, I've only tried to replace the button that needed changing `button("SPC f f", "ÔÄÇ  Find File  ", ":Telescope find_files<CR>"),`, but it didn't work. Then I simply copy>pasted the whole `buttons` section from `alpha.lua` which also didn't work.

---

This is my `chadrc.lua`.

```
local M = {}
local pluginConfs = require "custom.plugins.configs"
M.options, M.ui, M.mappings, M.plugins = {}, {}, {}, {}

-- make sure you maintain the structure of `core/default_config.lua` here,
-- example of changing theme:

M.plugins = {
  status = {


    alpha = true,
  },

  default_plugin_config_replace = {
     telescope = pluginConfs.telescope,
     alpha = pluginConfs.alpha,
  },
}

M.ui = {
   theme = "onejelly",
}
```

This is the `configs.lua`.

```
local M = {}
local function button(sc, txt, keybind)

-- make sure you maintain the structure of `core/default_config.lua` here,
-- example of changing theme:

M.telescope = {
        defaults = {
            prompt_prefix = "   ",
        },
}

M.alpha = {
  type = "group",
   val = {
      button("SPC f f", "something  Find File  ", ":Telescope find_files<CR>"),
      button("SPC f o", "something else Recent File  ", ":Telescope oldfiles<CR>"),
      button("SPC f w", "what  Find Word  ", ":Telescope live_grep<CR>"),
      button("SPC b m", "the  Bookmarks  ", ":Telescope marks<CR>"),
      button("SPC t h", "fudge  Themes  ", ":Telescope themes<CR>"),
      button("SPC e s", "omg Settings", ":e $MYVIMRC | :cd %:p:h <CR>"),
   },
   opts = {
      spacing = 1,
   },
  }

return M
```

---

I've confirmed that without the `alpha` part (so only with `telescope`) it works so it must be syntax related to `alpha`. I've hit a wall for several hours now trying to come up with a solution.

**Comment by siduck** [comment] 2022-04-12 04:30
its an iterm issue, please try it with kitty or alacritty or wezterm

**Comment by 89iuv** [comment] 2022-04-12 15:26
This is what worked for me:

chadrc.lua
```
local function button(sc, txt, keybind)
   local sc_ = sc:gsub("%s", ""):gsub("SPC", "<leader>")

   local opts = {
      position = "center",
      text = txt,
      shortcut = sc,
      cursor = 5,
      width = 36,
      align_shortcut = "right",
      hl = "AlphaButtons",
   }

   if keybind then
      opts.keymap = { "n", sc_, keybind, { noremap = true, silent = true } }
   end

   return {
      type = "button",
      val = txt,
      on_press = function()
         local key = vim.api.nvim_replace_termcodes(sc_, true, false, true)
         vim.api.nvim_feedkeys(key, "normal", false)
      end,
      opts = opts,
   }
end

-- Just an example, supposed to be placed in /lua/custom/

local M = {}

-- make sure you maintain the structure of `core/default_config.lua` here,
-- example of changing theme:

M.options = {
   relativenumber = true,
}

M.ui = {
   theme = "catppuccin",
}

M.plugins = {
  status = {
    alpha = true -- dashboard
  },
  options = {
    statusline = {
      style = "block" -- default, round , slant , block , arrow
    }
  },
  default_plugin_config_replace = {
    nvim_tree = {
     git = {
        enable = true
      }
    },
    telescope = {
      defaults = {
        prompt_prefix = " Ôê¢  "
      }
    },
    alpha = {
      buttons = {
        type = "group",
        val = {
          button("SPC f f", "<Search Icon>  Find File  ", ":Telescope find_files<CR>"),
          button("SPC f o", "Ôúô  Recent File  ", ":Telescope oldfiles<CR>"),
          button("SPC f w", "Ôú¨  Find Word  ", ":Telescope live_grep<CR>"),
          button("SPC b m", "ÔÄÆ  Bookmarks  ", ":Telescope marks<CR>"),
          button("SPC t h", "Óà´  Themes  ", ":Telescope themes<CR>"),
          button("SPC e s", "Óòï  Settings", ":e $MYVIMRC | :cd %:p:h <CR>"),
        },
        opts = {
          spacing = 1,
        }
      }
    }
  }
}

return M
```

Explanation:
The way that alpha.lua builds the configuration for the dashboard is by using a function named "button" which is defined and accessible only in alpha.lua. What i did was to copy that function in my chadrc.lua in order to be able to create the alpha default object just like it is done in alpha.lua and replacing only the search icon.

I think that you can use the same approach to copy the "button" function to your configs.lua in order to build the alpha object from there, but i am not 100% sure it will work.

**Comment by 89iuv** [comment] 2022-04-12 16:58
> > its an iterm issue, please try it with kitty or alacritty or wezterm
> 
> .

I know it's an iterm issue and i can confirm that it works as expected with alacritty and kitty, but i need it to work with iterm and i am willing to change the icons in order to not have the "?" instead of the search icon.

**Comment by zbirenbaum** [comment] 2022-04-13 18:30
> > > its an iterm issue, please try it with kitty or alacritty or wezterm
> > 
> > 
> > .
> 
> I know it's an iterm issue and i can confirm that it works as expected with alacritty and kitty, but i need it to work with iterm and i am willing to change the icons in order to not have the "?" instead of the search icon.

First of all, why do you need it to work with iterm, there are tons of other great options? Second, if the font you are using between terms is the same, then there's no reason it should display the wrong icon.

If it's an issue with iterm and not NvChad, please make an issue post in their repository, as we won't be able to help you with upstream problems here.

If you can confirm it is an upstream problem, please close this post.

**Closed** 2022-04-13 18:31 UTC

**Comment by 89iuv** [comment] 2022-04-14 06:40
> > > > its an iterm issue, please try it with kitty or alacritty or wezterm
> > > 
> > > 
> > > .
> > 
> > 
> > I know it's an iterm issue and i can confirm that it works as expected with alacritty and kitty, but i need it to work with iterm and i am willing to change the icons in order to not have the "?" instead of the search icon.
> 
> First of all, why do you need it to work with iterm, there are tons of other great options?
> 
> If it's an issue with iterm and not NvChad, please make an issue post in their repository, as we won't be able to help you with upstream problems here. Since you have acknowledged this is a problem with iterm and not NvChad, I'm gonna go ahead and close this.

The reason why i need iTerm is because of the "quake mode" on mac. I know it is a silly reason but i really enjoy having the ability to switch to a fullscreen terminal window, over whatever i have opened on my desktop, at a press of a button. This feature is supported only in iTerm for mac as fas as i know.

You are right the issue opened (not by me) has nothing to do with nvchat.

Suggestion: Because a lot of mac users will use iTerm as theirs replacement for the default terminal emulator on mac, it would be nice to have a simple way to overwrite the icons from a user configuration file, or use a set of icons which are displayed corect on all terminal emulators.

**Comment by siduck** [comment] 2022-04-14 07:09
weird that iterm2 doesnt support that icon but supports most nerdfont icons

**Comment by zbirenbaum** [comment] 2022-04-14 09:16
> Suggestion: Because a lot of mac users will use iTerm as theirs replacement for the default terminal emulator on mac, it would be nice to have a simple way to overwrite the icons from a user configuration file, or use a set of icons which are displayed corect on all terminal emulators

I personally don’t use the dashboard, and honestly find the whole concept of one very un-‘vimlike’, so I really couldn’t care less if the icon changes for it, but I will say that even if @siduck would prefer not to change it, replacing the plugin config yourself can be done super simply.

1. Copy the config file for the dashboard plugin to your custom dir, edit that icon.
2a. Do it my preferred way and copy the table from the plugins init.lua in NvChad to you custom plugin table, and then literally just change the config statement to require that config same as anything else (NvChad won’t load plugins you already have listed in your plugin table) 
2b. Find whatever the dashboard config override path is from the table in plugins/init.lua and override it in the chadrc default_config_override.

To be perfectly honest, I think that if Mac users are going to be adamant that they will only use a single term emulator which has noticeable upstream bugs, I think it’s pretty reasonable to expect them to do the work regarding making their term function the way they want it to, rather than change everyone else’s experience so that they are forced to go through the override process if they want it back.

**Comment by stasimate** [comment] 2023-08-15 22:41
> weird that iterm2 doesnt support that icon but supports most nerdfont icons

i just changed the icon from https://www.nerdfonts.com/cheat-sheet
![image](https://github.com/NvChad/NvChad/assets/74570672/6e72b778-add1-4054-9810-285458e2181f)
